### ISSUE TITLE
How do I clean user’s token (i.e., on log out)?

### ISSUE THREAD

**Issue by oferRounds** [vmurin/react-native-azure-auth#10]

**Comment by vmurin** [comment]
Take a look on the example:
https://github.com/vmurin/react-native-azure-auth-sample/blob/master/App.js#L59

**Comment by vmurin** [comment]
We do not need to remove token from cache as it is always overwritten if the scope of the currently requested token ist the same or have intersection (inclusion). The expiration of any token is also handled. If expired, the token is refreshed and then the cache updated accordingly. So you will never get incorrect token from cache.
If you about "logout", so it is handled by Azure Cloud not by framework. After logout Azure invalidate the token, that could theoretically be valid and stay in cache. So you should properly implement login logic in your app and do not use `acquireTokenSilent` after logout. It means you have to save login state in the app as well.
