### ISSUE TITLE
Logout Issue on Android

### ISSUE THREAD

**Issue by dhruvatara** [vmurin/react-native-azure-auth#100]
Hello,
We are facing the same issue as issue #37 
I am currently using Firefox Lite browser on my device while testing, and after closing the logout tab it does not redirect back to the android application. Please advise.

Currently we are using v1.2, yet the issue persists

**Comment by vmurin** [comment]
Hi 
the issue #37 is about not closing azure window automatically after successful logout. And as explained in #36 & #37 - it is not possible for azure + android.
But after closing browser activity the system should be back to your app. You wrote "logout tab" - actually  you should close the entire firefox app to return to calling activity (your app). It is just standard android behavior, nothing specific to library...

Additionally you can try to use `post_logout_redirect_uri` query parameter - see this [question](https://stackoverflow.com/questions/45935305/azure-ad-logout-url-not-redirecting) on the stackoverflow.

As a value for `post_logout_redirect_uri` you should specify some URL with a scheme of you app like this:
``` 
{YOUR_APP_PACKAGE_NAME}://{YOUR_APP_PACKAGE_NAME}/logout
```

**Comment by dhruvatara** [comment]
I tried closing the browser app and it made no change- the app still does not register a successful logout

**Comment by vmurin** [comment]
have you tried `post_logout_redirect_uri ` ?

**Comment by vmurin** [comment]
closed due to inactivity and missing feedback
