### ISSUE TITLE
in app browser: sign in loads indefinitely

### ISSUE THREAD

**Issue by Venipa** [vmurin/react-native-azure-auth#101]
MSAL generated deep link url (provided from azures generated mobile auth preset):
![image](https://user-images.githubusercontent.com/17952364/91908142-64a02100-ecab-11ea-8acd-deb084f4aede.png)

AzureAuth init:
![image](https://user-images.githubusercontent.com/17952364/91907925-083d0180-ecab-11ea-9c97-81254cc6a9ba.png)

Sign in loading...:
![image](https://user-images.githubusercontent.com/17952364/91907774-bd22ee80-ecaa-11ea-92dd-b1f4434fa381.png)

**Comment by Venipa** [comment]
according to remote devtools it seems that the navigation is getting blocked:
![image](https://user-images.githubusercontent.com/17952364/91909036-c6ad5600-ecac-11ea-899c-a4ec7abc6591.png)

**Comment by vmurin** [comment]
Hi,
sorry for the delay with the answer. 

It's a typical error if the registered callback URL does not correspond to one in `AndroidManifest.xml`

You could check the issue #6 

And I really recommend first to follow the URL scheme from [README](https://github.com/vmurin/react-native-azure-auth#callback-urls) and remove all other `<data />` entries from manifest.
Check if it works in this configuration and then add other entries if you need it for some reason.

You could also check the [sample app](https://github.com/vmurin/react-native-azure-auth-sample) and just register some test application in Azure Portal with exactly the sample callback URL

**Comment by Venipa** [comment]
> Hi,
> sorry for the delay with the answer.
> 
> It's a typical error if the registered callback URL does not correspond to one in `AndroidManifest.xml`
> 
> You could check the issue #6
> 
> And I really recommend first to follow the URL scheme from [README](https://github.com/vmurin/react-native-azure-auth#callback-urls) and remove all other `<data />` entries from manifest.
> Check if it works in this configuration and then add other entries if you need it for some reason.
> 
> You could also check the [sample app](https://github.com/vmurin/react-native-azure-auth-sample) and just register some test application in Azure Portal with exactly the sample callback URL

the callback url does correspond to one in AndroidManifest.xml

i've tried to load such callback via adb shell and it worked, please look into my second comment which also shows the issue after calling the custom scheme @vmurin

**Comment by vmurin** [comment]
At time as you are putting in the password in browser and the app should be called back - there is no any library code involved. 
Via adb you are using one URL, and what uses Azure on login - it's another thing. If your app does not pop up on callback, it means that the Azure server calls something not registered in AndroidManifest.
That's why my advise was - remove any other callback URLs in the manifest *and* in the app registration. And as I wrote - the simplest way is  to check out sample app and register it with one callback to see whether it works

I'm looking forward to your feedback :)

**Comment by Venipa** [comment]
> according to remote devtools it seems that the navigation is getting blocked:
> ![image](https://user-images.githubusercontent.com/17952364/91909036-c6ad5600-ecac-11ea-899c-a4ec7abc6591.png)

please look into my previous comments...
i've tried every custom scheme provided in the AndroidManifest.xml
these schemes are blocked.

**Comment by vmurin** [comment]
please look into my previous comment - I explained, that it can not has to do with library.
And I cannot see in you comments that you tried anything that I supposed to. ;)

If you are asking for an advise:
- just try the simplest possible configuration on both sides - manifest and app registration - only 1 URL. 
- I don't have any clue where this "navigation blocked" comes from. And also I'm not sure that the error message in this case means exactly wat it says... it could be some side effect - so I would try another clean copy of android emulator, perhaps another version.

Sorry, I can't propose any other suggestion about your issue. The library is downloaded about 800 times a week - and it just works. Your should definitely have some configuration issue. Just give a try for my suggestions above :-)

**Comment by Venipa** [comment]
> please look into my previous comment - I explained, that it can not has to do with library.
> And I cannot see in you comments that you tried anything that I proposed to. ;)
> 
> If you are asking for an advise:
> 
> * just try the simplest possible configuration on both sides - manifest and app registration - only 1 URL.
> * I don't have any clue where this "navigation blocked" comes from. And also I'm not sure that the error message in this case means exactly wat it says... it could be some side effect - so I would try another clean copy of android emulator, perhaps another version.
> 
> Sorry, I can't propose any other suggestion about your issue. The library is downloaded about 800 times a week - and it just works. Your should definitely have some configuration issue. Just give a try for my suggestions above :-)

Pt 2. This issue comes from a real device, the error popped up in a chromium browser. Probably one of the new security updates.

**Comment by vmurin** [comment]
Oh, it's an important addition. Does it works on emulator?

**Comment by Venipa** [comment]
> Oh, it's an important addition. Does it works on emulator?

I've also tried it on an android emulator with google play services.
Android 10 (both emulator and real device)
Chrome 85.0+, Firefox 80.1.2+ and Edge 45.07

**Comment by vmurin** [comment]
Some suggestion:
https://developer.android.com/training/app-links/deep-linking#adding-filters
Quote from here:
> Notice that the two intent filters only differ by the <data> element. Although it's possible to include multiple <data> elements in the same filter, it's important that you create separate filters when your intention is to declare unique URLs (such as a specific combination of scheme and host), because multiple <data> elements in the same intent filter are actually merged together to account for all variations of their combined attributes.

It could be that multiple `data` elements create some combination that is blocked then by browser. Have you tested the behavior with only one callback ULR == one `data` elemen in the `intent-fliter`? try it.

**Comment by Venipa** [comment]
> Some suggestion:
> https://developer.android.com/training/app-links/deep-linking#adding-filters
> Quote from here:
> > Notice that the two intent filters only differ by the <data> element. Although it's possible to include multiple <data> elements in the same filter, it's important that you create separate filters when your intention is to declare unique URLs (such as a specific combination of scheme and host), because multiple <data> elements in the same intent filter are actually merged together to account for all variations of their combined attributes.
> 
> It could be that multiple `data` elements create some combination that is blocked then by browser. Have you tested the behavior with only one callback ULR == one `data` elemen in the `intent-fliter`? try it.

I'm trying it asap and respond with the result

**Comment by Venipa** [comment]
this has been fixed by adding the package name as "android:label" attribute to the intent filter (thanks to microsoft support)

**Comment by vmurin** [comment]
> this has been fixed by adding the package name as "android:label" attribute to the intent filter (thanks to microsoft support)

Thank you very much for your feedback.
I didn't have time to write you yesterday - I have tested the flow within you environment (Android 10 + Chrome 85) and it worked as intended. :) 

Actually I can't imagine that _label_ can have any impact on functionality. May be you have changed something else during your bug-hunt ;)
I thought - the one more possible problem could be some not allowed character in scheme. See *Note 2* [in this section](https://github.com/vmurin/react-native-azure-auth#callback-urls)

And for the case if someone else has a similar issue could you please post here you manifest example as a reference.
Thank you in advance!
