### ISSUE TITLE
Does this library work with Expo? I tried using this library but got null error when evaluating AzureAuth.bundleIdentifier

### ISSUE THREAD

**Issue by namakujuo** [vmurin/react-native-azure-auth#103]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/66373379/97304975-e1c2bf00-1832-11eb-8c72-561483365e7e.png)

**Comment by vmurin** [comment]
Hi 
the question is already answered here - issue #87 
(that's why it is marked as _good first issue_  ;-)  )

Regards
Vlad
