### ISSUE TITLE
Null is not an object (evaluating 'AzureAuth.bundleIdentifier')

### ISSUE THREAD

**Issue by namakujuo** [vmurin/react-native-azure-auth#104]
Is this a common error? Having trouble using this library on android

![error](https://user-images.githubusercontent.com/66373379/97624625-bf30d180-19fd-11eb-8436-66b98645d231.png)

**Comment by vmurin** [comment]
Hi
please check if it is your issue
https://stackoverflow.com/questions/57341408/ensure-that-the-applications-info-plist-contains-a-value-for-cfbundleidentifier
or this one (same cause)
https://stackoverflow.com/questions/51487867/react-native-run-ios-the-bundle-identifier-of-the-application-could-not-be-dete/51487987

**Comment by namakujuo** [comment]
Thanks for the reply

The links seem to be for ios. I'm running on android and still getting the issue

**Comment by vmurin** [comment]
Could it be, hat you did not linked the native modules?
See [Installation](https://github.com/vmurin/react-native-azure-auth#installation) section of README.md

**Comment by namakujuo** [comment]
I've done the link command for both the library and AsyncStorage and still getting the bundleIdentifier erorr.

**Comment by vmurin** [comment]
What I could suppose for you to debugg, is to check out the [sample app](https://github.com/vmurin/react-native-azure-auth-sample) and try to link, build and start it - if you will not get any errors, just compare settings, property files etc from the sample and your app.

**Comment by vmurin** [comment]
@namakujuo 
Could you please leave a short feedback - how did you solve the problem. It could help someone else :)
Thanks in advance!

**Comment by namakujuo** [comment]
I'm sorry I closed it by mistake. My issue still persists. I ran into errors when trying out the sample. It was giving me a regular expression error in node modules error.

**Comment by namakujuo** [comment]
Issue I believe is that I was running on react-native version 63.3 while this library only works on react-native version 61.4

So: 
-downgrade react-native version
-delete node modules
-reinstall (npm/yarn install)
-delete the app from android simulator
-rebuild the app on android simulator (react-native run-android)

and it should work

**Comment by vmurin** [comment]
FYI: I have just updated the sample app project to RN 0.63.3 - all works. Check it out :)
