### ISSUE TITLE
Client ID and aud from JWT payload doesn't match 

### ISSUE THREAD

**Issue by vrpratheep22** [vmurin/react-native-azure-auth#107]
I've generated an access token as per the steps mentioned in the documentation but I couldn't see the aud from jwt payload match the client id which I obtained from registering my application on Azure

I've done azure authentication in react using react adal where the jwt payload aud and my client id remain same .

**Comment by vmurin** [comment]
Normally you are receiving 3 Tokens - ID Token, Access Token and Refresh Token - please check what token you are comparing with.
Library does not do any manipulations with tokens and take it over as is.
I close the issue as not related to library directly.

Besides this I do not know if the ADAL Library actively maintained last years. I could be it uses the V1 endpoints. And the answers from V1 and V2 endpoints from Azure are not consistent. So this question is more for Microsoft :)
