### ISSUE TITLE
React Native Community Async Storage is deprecated

### ISSUE THREAD

**Issue by michPhil** [vmurin/react-native-azure-auth#108]
Hi. I wanted to implement this library to enable Microsoft SSO. However, I found out that @react-native-community/async-storage has been deprecated. So I have tried using the newer one and it does not work with this library but it causes errors.

May I know if this library will upgrade to the latest version for async storage?

https://www.npmjs.com/package/@react-native-community/async-storage

**Comment by vmurin** [comment]
Hi,

I will check the issues and upgrade ASAP

**Comment by chill0216** [comment]
Any update on this? Running into the same issue.

**Comment by vmurin** [comment]
Library update to version 1.7.0 with the new AsyncStorage.

Please check the sample Application for usage example:  https://github.com/vmurin/react-native-azure-auth-sample

See the changed files in the sample - on the update I had only couple native module linking issues there (duplicating) - it is easy to fix - just remove duplicated lines.
