### ISSUE TITLE
Cannot read property 'bundleIdentifier' of undefined when trying to test using Jest

### ISSUE THREAD

**Issue by dhruvatara** [vmurin/react-native-azure-auth#109]
Tried running npm test on my RN app that uses this library, the test keeps failing with the following error.

![image](https://user-images.githubusercontent.com/36121933/106831297-86c81180-6644-11eb-9237-49a6676364d0.png)

**Comment by vmurin** [comment]
Hi,

this library uses native modules (particularly by accessing bundleIdentifier) which can not be tested with Jest.
Please look here for mocking https://jestjs.io/docs/en/tutorial-react-native#mock-native-modules-using-jestmock
And the issue #87  is probably  also could be useful for you if you are using Expo.
