### ISSUE TITLE
Question: callback opens app on Beta, but fails on Google Play’s version

### ISSUE THREAD

**Issue by oferRounds** [vmurin/react-native-azure-auth#11]
Facing a strange issue: on Android, when I tested on Beta (sent via Crashlytics) the SSO worked perfect. 

But after submitting it to Google Play, when I download the version, it seems that the callback does not trigger the app launch. The user get stuck after completing the login on the Microsoft page.

Any idea why that might happen?

**Comment by oferRounds** [comment]
![img-20181220-wa0002](https://user-images.githubusercontent.com/1477963/50308374-b0913f00-04a3-11e9-8971-bbf812e7a948.jpg)

It gets stuck here, the "loading-dots" continue their animation forever

**Comment by vmurin** [comment]
Hi could it be, that you are using two different MS app-registrations for "dev" and "production" apps, and the app pushed to GooglePlay ("prod") uses different registration where the call back URL differs from the "dev" app?
Again - it's the typical behavior by Callback-URL mismatch in the MS cloud an the app as pointed in the issue #6 

Another possible reason - in the issue #9  you wrote, that you have added host attribute. It could be that it works then only on emulator, where the host = localhost. I'm not sure.

**Comment by oferRounds** [comment]
Thank you! I had a problem with the definition on the Manifest, sorry about that!

Thank you for your support, the library is awesome!

**Comment by vmurin** [comment]
Glad to hear that you have found the problem.
Good luck with the app and Marry Christmas + happy New Year ! :-)))

**Comment by oferRounds** [comment]
Thank you, to you too: :) :)
