### ISSUE TITLE
Refresh ID token

### ISSUE THREAD

**Issue by shilomagen** [vmurin/react-native-azure-auth#110]
First, thanks for this amazing library, helped me so much.
Second, I need to refresh idToken but I couldn't find documentation of how I do it, I saw that in the implementation you do persist the refresh token on the cache but hide it from the response.
So my question is, how do I keep refreshing my id token (not access token) and make sure the user is still activated?

Thanks!

**Comment by shilomagen** [comment]
@vmurin ? :)

**Comment by vmurin** [comment]
Hi Shilo,
sorry, I was 2 days on a business trip and could not answer your question.

You actually don't need the refresh token as it is automatically used if you call `acquireTokenSilent`
Tale a look on the [sample app](https://github.com/vmurin/react-native-azure-auth-sample/blob/3326769d5d2bef8124948b51fdc8b43946fd2a8c/App.js#L42)
The return value contains both: the access and id tokens

Regards
Vladimir

P.S. Feel free to reopen this issue if you have some troubles with this approach.

**Comment by shilomagen** [comment]
Thank you very much @vmurin, highly appreciated!
