### ISSUE TITLE
iOS Crash OS 14.5

### ISSUE THREAD

**Issue by janroures** [vmurin/react-native-azure-auth#113]
Hi,

iOS App crashes with OS=>14.5 

Fixed by adding 

`if (@available(ios 14.5, *)) {
        callbackURLScheme = [[NSURL URLWithString: queryItem.value] scheme];
    }`

under `NSString *callbackURLScheme = queryItem.value;`

in AzureAuth.m line 95

**Comment by vmurin** [comment]
Hi,

thank you very much for reporting this bug!
Could you please provide full exception message for it.

And It would be great if you create a Pull Request for your fix.

**Comment by janroures** [comment]
`2021-05-01 12:12:34.230954+0200 App[22305:107786] [AuthenticationSession] The provided scheme is not valid. A scheme should not include special characters such as ":" or "/".
2021-05-01 12:12:34.268024+0200 App[22305:107786] [native] Exception 'The provided scheme is not valid. A scheme should not include special characters such as ":" or "/".' was thrown while invoking showUrl on target AzureAuth with params (
    "https://login.microsoftonline.com/*****/oauth2/v2.0/authorize?scope=offline_access%20openid%20profile&clientId=******&response_type=code%20id_token&response_mode=fragment&state=*****&nonce=wRWBzzry0RUGCXPVErDwjNY35j1b3ENWRypDREQtPWA&code_challenge_method=plain&code_challenge=******&client_id=***&redirect_uri=msauth.com.package.name%3A%2F%2Fauth",
    0,
    0,
    239
)
callstack: (
0   CoreFoundation                      0x00007fff20422fba __exceptionPreprocess + 242
1   libobjc.A.dylib                     0x00007fff20193ff5 objc_exception_throw + 48
2   AuthenticationServices              0x00007fff4aae1b15 -[ASWebAuthenticationSession initWithURL:callbackURLScheme:usingEphemeralSession:completionHandler:] + 684
3   App                                        0x000000010373577a -[AzureAuth presentAuthenticationSession:usingEphemeralSession:] + 858
4   App                                        0x0000000103734f2c -[AzureAuth showUrl:usingEphemeralSession:closeOnLoad:callback:] + 268
5   CoreFoundation                      0x00007fff20429a3c __invoking___ + 140
6   CoreFoundation                      0x00007fff20426c6f -[NSInvocation invoke] + 305
7   CoreFoundation                      0x00007fff20426f02 -[NSInvocation invokeWithTarget:] + 70
8   Mediapro Access                     0x0000000103970114 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2660`

![2021-05-01](https://user-images.githubusercontent.com/8616333/116784247-813b6580-aa93-11eb-99a4-114a2526f612.png)


Sure I will submit a PR
