### ISSUE TITLE
Issue: MS request profile permissions every time i want to sign in my app

### ISSUE THREAD

**Issue by sfernandez11** [vmurin/react-native-azure-auth#12]
Hi! I'm having the following problem:

The first time I sign in to my App with a MS account (registration) it request me to accept the permissions according to the scope declared in `azureAuth.webAuth.authorize ({scope: ......});` and I think that it's OK.

The problem appears when I want to sign in again with my MS account, what happens is that every time I want to do this MS request me again to accept the permissions (MS don't remember that I already accept them in the registration) and i think that it's not okay and it is very annoying.

Is this problem related to this library or is it part of the configuration of the application in MS? Did someone have the same problem or know how to fix it?

Thanks

**Comment by vmurin** [comment]
Hi,

first sorry for the delay with the answer. I was on vacation and had no access to githab :) .

To your question: actually the user consent (accepted the permissions) is saved in your Azure account and can be checked in portal view (https://portal.azure.com/) - look in the AD menu item... can not tell you now the exact path.
But you can also force user to give the permission every time the user login. You can do it with the app by sending parameter `webAuth.authorize({..., prompt: "consent", ...})`

Regards
Vladi
