### ISSUE TITLE
Can´t select the checkbox ID tokens cause it doesnt appear

### ISSUE THREAD

**Issue by luismiguelmena** [vmurin/react-native-azure-auth#121]
In the documentation said: Select Public client (mobile & desktop) from dropdown. And latter: Select checkbox ID tokens in the Implicit grant section.
But for public client this option doesnt appear, what can i do?

**Comment by vmurin** [comment]
Hi,
 
you a right! The library uses so called "hybrid flow" - look [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow). It means - the the call sequence is from "authorization flow" but additionally we get the "id_token".

To enable "id_token" you relay need to add "Web platform" - and select checkbox ID tokens. As a redirect URL just put https://localhost

Feel free to reopen issue if you encounter some troubles :)
