### ISSUE TITLE
[QUESTION] Edit User Profile

### ISSUE THREAD

**Issue by weyron2014** [vmurin/react-native-azure-auth#132]
Hi guys,

I am trying to add an Edit Profile user flow to my application. 
I've edited the`authorityUrl` with `.authorize` method and it works, but it requires a new sign up/sign in even if the user is authorized. 
Is there are any ways we can pass the `userId` to `.authorize` method to check if the user is signed in or any other ways to skip the unnecessary Sign In/Sign Up for the Authorized users while using other user_flows except SignUp/SignIn?

Thanks a lot!

**Comment by weyron2014** [comment]
@vmurin Could you open the issue again? Still unresolved. Thanks a lot!

**Comment by vmurin** [comment]
Sorry, I don't have any experience with B2C. But I assume the general approach should be the same - you have some API to edit the profile and need access token with according scopes to be able access the API. You can get the token using the library and then use Profile API for editing.
It it works in anther way - you have to investigate it by yourself.
It could be that only MSAL library supports special B2C features.

**Comment by vmurin** [comment]
The original question seems to address user interaction with Azure portal and not handled by the library.
Closing as not related.
