### ISSUE TITLE
Hide the address bar

### ISSUE THREAD

**Issue by edwardkes** [vmurin/react-native-azure-auth#134]
Is it possible to hide the address bar when the Azure auth pops for the user?
I dont want the user to see the address bar at all, not only the url itself...

Side note:
Do you use the Chrome custom tabs to open the url?

**Comment by vmurin** [comment]
In fact, Chrome Custom Tabs is designed to display a web page where the user is sure that the programmer of that software does not have a phishing, like a bank payment or authentication page as in our case.

Yes, Chrome Custom  Tabs are used and in this use case the switch to Trusted Web Activities to hide URL bar is **not possible**, as we cannot publish  _Digital Asset Links JSON_ file on Azure.
