### ISSUE TITLE
iOS build issue

### ISSUE THREAD

**Issue by oferRounds** [vmurin/react-native-azure-auth#135]
Hey!
I’m using both react-native-azure-auth and and react-native-app-auth (for Okta), and when upgrading to the latest React Native (0.66.4), I get the build error:

```
duplicate symbol '_taskId' in:
    /Users/ofermorag/Library/Developer/Xcode/DerivedData/Bob-dpwnvbctalxyjoeirqcjffdjgulu/Build/Products/Debug-iphoneos/AzureAuth/AzureAuth.framework/AzureAuth(AzureAuth.o)
    /Users/ofermorag/Library/Developer/Xcode/DerivedData/Bob-dpwnvbctalxyjoeirqcjffdjgulu/Build/Products/Debug-iphoneos/react-native-app-auth/react_native_app_auth.framework/react_native_app_auth(RNAppAuth.o)
ld: 1 duplicate symbol for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I use the latest react-native-azure-auth version (1.8.1)

Any idea how to solve it? Thanks!

**Comment by oferRounds** [comment]
Hi @vmurin, do you have any idea how to solve this issue?

Thanks!

**Comment by vmurin** [comment]
Sorry, I don't have currently any idea

**Comment by oferRounds** [comment]
Ok, found a fix for this on the conflicting library:
https://github.com/FormidableLabs/react-native-app-auth/pull/697

I think it might be worth changing the `taskId` variable on your side also, if indeed has such one

**Comment by vmurin** [comment]
> Ok, found a fix for this on the conflicting library: [FormidableLabs/react-native-app-auth#697](https://github.com/FormidableLabs/react-native-app-auth/pull/697)
> 
> I think it might be worth changing the `taskId` variable on your side also, if indeed has such one

Hey, thanks for the hint! On the first try I did not fount the variable, but now I see that it exists and will change it in the next patch version!

**Comment by oferRounds** [comment]
Awesome! Thanks!
