### ISSUE TITLE
[QUESTION] Authorization code flow

### ISSUE THREAD

**Issue by qsdamar** [vmurin/react-native-azure-auth#137]
Hello and thank you for such a good library.

My question is, is there a way to obtain an authorization code after successful login? Currently, I'm obtaining _accessToken_ and _rawIdToken_ after login (using azureAuth.webAuth.authorize({...})), but that's not what I need to pass to the backend. What I need to pass to the backend, is _authorizationCode_.

I've read the whole documentation and issues and did not find anything helpful on that.

Thanks in advance.

**Comment by vmurin** [comment]
Hi,
the _authorizationCode_ is exchanged during authentication flow against accessToken & refreshToken. That's actually all what you need to access Azure services in behalf of logged in user. 

Probably if you explain why do you need authorizationCode I would be able to help you :)

Kind regards
Vlad

**Comment by qsdamar** [comment]
Hi Vlad, thank you for the reply.

The reason why I need authorizationCode is to pass that to the backend where the user will be verified. That's how the auth flow is managed.

**Comment by vmurin** [comment]
I suppose you are mixing up some terms. _authorizationCode_ from this flow is only meant to be verified and exchanged by Azure and not some custom backend. If you need to extract some custom claims - what you need is "rawIdToken" (it is a property of accessToken) - not decoded IdToken - you can pass it to backend to extract custom claims. You will not find anything like this in _authorizationCode_

Just check the rawIdToken - I think you will find there what you need :)

**Comment by raajnadar** [comment]
This is how we fetch access token and refresh token on the backend https://docs.microsoft.com/en-us/advertising/guides/authentication-oauth-get-tokens by proving the auth code.

similar to https://github.com/react-native-google-signin/google-signin/issues/673#issuecomment-517121190 for google calendar we send authorization code and get back access token and refresh token on our backend.

This is useful when we need to have access to services like outlook calendar to send data to outlook later when some event occurs in mobile apps. We cannot fetch access token every now and then for each event the heavy lifting is done on the secure env will backend.

**Comment by raajnadar** [comment]
@vmurin you just need to change and send the auth code with the response, those who need auth code will use auth code, and those who need an access token will use the access token.

https://github.com/vmurin/react-native-azure-auth/blob/23387d938ab846f26a4392e1b4c5ae19bf733cf5/src/webauth/index.js#L98

We need this value in the response of  `azureAuth.webAuth.authorize`

**Comment by raajnadar** [comment]
We store auth code of the account on our server and fetch access token and refresh token when required directly from the server. Like adding or removing calendar events from the server and not through the mobile app.

With auth code, we can get the access token and refresh token directly from the google or Microsoft service. I gave a link in that you can see how we do with Google OAuth.

**Comment by vmurin** [comment]
> We store auth code of the account on our server and fetch access token and refresh token when required directly from the server. Like adding or removing calendar events from the server and not through the mobile app.
> 
> With auth code, we can get the access token and refresh token directly from the google or Microsoft service. I gave a link in that you can see how we do with Google OAuth.

That makes no sense to save auth.code. The code is a one-time token (entity) and can not be reused!

https://stackoverflow.com/questions/26425578/why-does-the-oauth-2-0-specification-prevent-re-use-of-authorization-codes

You end-goal is finally to obtain access and refresh tokens - it is done by this library automatically for you. Now you can save this tokens on your server if you wish and reuse them if needed.

**Comment by raajnadar** [comment]
But you don't expose refresh token how is that useful? We only get access token and rawIdToken

**Comment by vmurin** [comment]
> But you don't expose refresh token how is that useful? We only get access token and rawIdToken

You can easily access refresh token like this after login (i.e. `authorize(...)` function successfully completed )

```javascript
console.log('Refresh token:', await azureAuth.auth.cache.getRefreshToken(tokens.userId));
```
