### ISSUE TITLE
prefersEphemeralWebBrowserSession input from code

### ISSUE THREAD

**Issue by Madhuri315** [vmurin/react-native-azure-auth#138]
prefersEphemeralWebBrowserSession is always false by default.. No provision from webAuth.authorize method to add ephemeralSession property

**Comment by Madhuri315** [comment]
authorize(options: {
    prompt?: string;
    scope?: string;
  }): Promise<BaseTokenItem & Partial<AccessTokenItem>>;
  
 ephemeralSession?: boolean, is missing here

**Comment by vmurin** [comment]
Fixed long time ago with PR  GH-111
