### ISSUE TITLE
Not able to install plugin

### ISSUE THREAD

**Issue by PragyaSingla** [vmurin/react-native-azure-auth#139]
Getting below error while installing using yarn:

error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote https://github.com/vmurin/js-base64.git HEAD
Output:
fatal: unable to access 'https://github.com/vmurin/js-base64.git/': SSL certificate problem: self signed certificate in certificate chain

Below error while installing using npm:

! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-native-azure-auth@1.8.2
npm ERR! node_modules/react-native-azure-auth
npm ERR!   react-native-azure-auth@"*" from the root project

Please help me to resolve this issue.

**Comment by vmurin** [comment]
Hi, 
it should be some proxy or firewall issue. Probably you are in some corporate network or using some VPN or something else...
In any case it is not related to the package you are installing.

**Comment by vmurin** [comment]
I will close issue as not directly related to library

**Comment by OshedheMunasinghe** [comment]
So I am in the windows proxy setting.. which one shall I edit? 
Strange that this package can't be installed but other npm-plug ins can ...
_Does it have to be complicated to install?_
