### ISSUE TITLE
How to use this library, if i do not require nonce in my jwt

### ISSUE THREAD

**Issue by SahilRS200** [vmurin/react-native-azure-auth#14]
Hi,
My existing backend server does not support jwt token which comes with a 'nonce' header. how can i generate a jwt token without nonce, as the nonce aspect is hard coded into the library, and i can't seem to be able to override them

**Comment by vmurin** [comment]
Hi,

Nonce is a required part of request and response in OpenID Connect. See MS documentation here:

https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-openid-connect-code#send-the-sign-in-request

We can not remove it as it's a part of standard.

**Comment by abdulrahman18** [comment]
![image](https://user-images.githubusercontent.com/31540549/57197688-fbf64680-6f87-11e9-9fb0-724838caedc4.png)

![image](https://user-images.githubusercontent.com/31540549/57197692-0b758f80-6f88-11e9-8df0-9a2f9b67e9cf.png)

@vmurin I checked the response access token in jwt. But It shows an invalid signature. Can you help me?

**Comment by abdulrahman18** [comment]
@SahilRS200 Can you help me for jwt token issue. Are you fixed on this? I think your issue also same like this right?
