### ISSUE TITLE
Don't keep activities Android

### ISSUE THREAD

**Issue by joaovtpereira** [vmurin/react-native-azure-auth#141]
Hi,

I'm having a problem on some devices in the login flow. After the user signs In, the app restarts from scratch and the login flow cannot be terminated. I found that the problem refers to the 'Don't keep activities' option being enabled on some devices. Has anyone dealt with this problem and have a solution?

**Comment by vmurin** [comment]
>Don't keep activities under the Developer Options menu. When this option is enabled, the Android OS will destroy an activity as soon as it is stopped. It is intended to help developers debug their apps. For example, it can simulate the case that Android will kill an activity in the background due to memory pressure. In normal use, it is not recommended to turn this option on because this may lead to unexpected issues on the apps, such as freezes, force closes and reboots.

The edge case issue is on developer devices only.
