### ISSUE TITLE
IOS build error for conflicting variables

### ISSUE THREAD

**Issue by raajnadar** [vmurin/react-native-azure-auth#143]
<img width="902" alt="azure" src="https://user-images.githubusercontent.com/17236768/167718923-d62d7f2c-2595-4c5b-bbe6-349d4bd9db99.png">

Showing All Errors Only
<path>/node_modules/react-native-azure-auth/ios/AzureAuth.m:81:30: Implicit declaration of function 'RCTMakeError' is invalid in C99

Showing All Errors Only
<path>/node_modules/react-native-azure-auth/ios/AzureAuth.m:81:30: Declaration of 'RCTMakeError' must be imported from module 'React.RCTUtils' before it is required

Showing All Errors Only
<path>/node_modules/react-native-azure-auth/ios/AzureAuth.m:81:30: Conflicting types for 'RCTMakeError'

Can we get this solved? RN 0.64.3 and expo SDK 44

Related issue for other packages https://github.com/expo/expo/issues/15622#issuecomment-997141629

**Comment by vmurin** [comment]
Hi Nadar,

thanks for reporting! The problem should be fixed in release 1.8.3
I will appreciate a short feedback

**Comment by vmurin** [comment]
Another important consideration: this library is non meant to be used in expo mode. So you should actually eject first to be able use it.

I think it is the main reason for the problem and will close the issue.
Feel free to reopen if you have a new input

**Comment by raajnadar** [comment]
I am using expo bare workflow, I was aware that this package won't work with expo go as we have native dependencies.

**Comment by vmurin** [comment]
OK. Then try please the new release

**Comment by amanraj0505** [comment]
I am getting the following error:
Undefined symbols for architecture x86_64:
  "_RCTMakeError", referenced from:
      -[AzureAuth presentSafariWithURL:] in AzureAuth.o
  "_RCTRegisterModule", referenced from:
      +[AzureAuth load] in AzureAuth.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

with 
"react": "17.0.2",
"react-native": "0.67.2",
"react-native-azure-auth": "^1.8.4",

any suggestion??

**Comment by amanraj0505** [comment]
Using react native CLI

**Comment by amanraj0505** [comment]
<img width="831" alt="Screenshot 2022-11-08 at 1 19 32 PM" src="https://user-images.githubusercontent.com/44123069/200504949-60104405-f742-42d7-b813-8a5ab94066f4.png">

**Comment by nizzam** [comment]
> <img alt="Screenshot 2022-11-08 at 1 19 32 PM" width="831" src="https://user-images.githubusercontent.com/44123069/200504949-60104405-f742-42d7-b813-8a5ab94066f4.png">

Have found any solution ?
