### ISSUE TITLE
Can we initialize azureAuth variable with dynamic clientId?

### ISSUE THREAD

**Issue by Vineet15** [vmurin/react-native-azure-auth#146]
Hi, thanks for the library. I have successfully installed the library and is working fine in iOS. I have one requirement for my project which is same application is used to log into multiple domains. 

So my question is, is there a way to initialize azureAuth variable without client ID?

**Comment by vmurin** [comment]
Hi,
I am not sure what you mean with "multiple domains"...
Do you want to use multiple registered Azure apps? Do you want to manage multiple Azure tenants with the same app?

Any way you can create multiple instances of azureAuth objects with different parameters.  
https://vmurin.github.io/react-native-azure-auth/AzureAuth.html

**Comment by Vineet15** [comment]
Yes by multiple domains I mean multiple Azure tenants with same app. Is there a way to invoke login page without creating instance of azureAuth object?

**Comment by vmurin** [comment]
unfortunately it is impossible
