### ISSUE TITLE
Not getting a refresh token

### ISSUE THREAD

**Issue by jeroenvanhattem** [vmurin/react-native-azure-auth#147]
```
let tokens = await azureAuth.webAuth.authorize({ scope: 'offline_access User.Read Calendars.Read Calendars.Read.Shared', prompt: 'consent', }).then((res: any) => {
        return res
      })
```

I use this code to authenticate a user. I get an accessToken, rawIdToken and other information returned. I do however not receive a refresh token. The scopes returned by this response do also not include the offline_access scope.

Am I missing something?

**Comment by vmurin** [comment]
`offline_access `  is added by default. try to replace it with `openid`

Look an example in the [sample app](https://github.com/vmurin/react-native-azure-auth-sample/blob/3326769d5d2bef8124948b51fdc8b43946fd2a8c/App.js#L29)

**Comment by jeroenvanhattem** [comment]
@vmurin I have tried the sample app, but it's also not giving me a refresh token. Is there a specific function I need to call to receive it?

**Comment by vmurin** [comment]
Ahh, you are right!
There was already same question. Look at the issue #67

**Comment by jeroenvanhattem** [comment]
@vmurin I need the refresh token in order to send it to my server. My server handles Microsoft Graph stuff to allow for multiplatform (mobile and web) use. Are there future plans for a getRefreshToken function? That'd be really great!

**Comment by vmurin** [comment]
You can easily access refresh token like this after login (i.e. `authorize(...)` function successfully completed )

```javascript
console.log('Refresh token:', await azureAuth.auth.cache.getRefreshToken(tokens.userId));
```

See sample App [login example](https://github.com/vmurin/react-native-azure-auth-sample/blob/3326769d5d2bef8124948b51fdc8b43946fd2a8c/App.js#L29)

**Comment by jeroenvanhattem** [comment]
It works. Amazing. Thank you so much for your very quick responses!
