### ISSUE TITLE
"We're unable to complete your request"

### ISSUE THREAD

**Issue by MatteoPuccio** [vmurin/react-native-azure-auth#154]
I tried the code snippet proposed in the usage section

try {
      let tokens = await azureAuth.webAuth.authorize({scope: 'openid profile User.Read Mail.Read' })
      this.setState({ accessToken: tokens.accessToken });
      let info = await azureAuth.auth.msGraphRequest({token: tokens.accessToken, path: '/me'})
      this.setState({ user: info.displayName, userId: tokens.userId })
    } catch (error) {
      console.log(error)
}

Unfortunately, after inserting the email the following image appears in the WebView:

![image](https://user-images.githubusercontent.com/82228938/181918149-b68509ac-aa10-4380-abda-14f8ed5ab144.png)

**Comment by vmurin** [comment]
should be a temporary issue on server side
