### ISSUE TITLE
override authorityUrl without /authorize

### ISSUE THREAD

**Issue by nexthor** [vmurin/react-native-azure-auth#155]
I have this issue, I'm trying to connect my app with B2C but I have a custom URL so, every time that I've tried to make a login always redirects to https://customUrl/authorize, but that resource doesn't exists.

is there a way to override or remove the /authorize subfix from login url?

![image](https://user-images.githubusercontent.com/10407896/184418482-fcfe5899-42a7-4637-9ff0-1123dbd3725b.png)

**Comment by vmurin** [comment]
Shortly - no, in current version of the library it's not possible. But any pull requests to make it possible are welcome! :) 🙏

On the other hand I don't see any variants of authorization URL without 'authorize' path. See docs: https://docs.microsoft.com/en-us/azure/active-directory-b2c/b2clogin

**Comment by nexthor** [comment]
sounds good, I'm going to create a new branch an make this change asap, thanks
