### ISSUE TITLE
Error while Authenticating with Azure React Native

### ISSUE THREAD

**Issue by amanraj0505** [vmurin/react-native-azure-auth#156]
Versions of the Libraries:

"react-native-azure-auth": "^1.8.0",
"react": "17.0.1",
"react-native": "0.64.0"

While Authentication after we sign-in from from the browser getting the following error and unable to signin:

**"Error during Azure operation [TypeError: fetch is not a function. (In 'fetch(url, options)', 'fetch' is false)]"**

Any suggestion or Fix?

**Comment by vmurin** [comment]
It looks like you took sample application and changed something in `onLogin` method. Probably you have an variable name conflict. 
Suggestion:  debug the code and check where the exception came from.

For now I will close the issue. Due to the time passed it is probably not current any more.
