### ISSUE TITLE
how can I add accessibilityLabel to the microsoft sign in page

### ISSUE THREAD

**Issue by LayMui** [vmurin/react-native-azure-auth#157]

**Comment by vmurin** [comment]
Hi Lay,

any features, design and other things on the login page are controlled by Microsoft i.e. - your MS account and not the auth library.
See for example https://support.microsoft.com/en-us/account-billing/accessibility-features-for-the-microsoft-account-website-c4610278-a5b9-d85c-0308-0619d0cc3e11
