### ISSUE TITLE
Not build apk android 

### ISSUE THREAD

**Issue by joomoodle** [vmurin/react-native-azure-auth#166]
Task :react-native-azure-auth:verifyReleaseResources FAILED

 buildToolsVersion = "31.0.0"
 minSdkVersion = 21
 compileSdkVersion = 31
targetSdkVersion = 31

**Comment by vmurin** [comment]
In the build.gradle file located in
node_modules/react-native-orientation/android/build.gradle made sure to
match the compileSdkVersion and buildToolsVersion with the one being used
in android/build.gradle.

Then run ./gradlew clean && ./gradlew assembleRelease to generate the APK.

Dont forget to write Feedback Here ;)

Juan Pablo ***@***.***> schrieb am Sa., 24. Dez. 2022, 05:09:

**Comment by georgetk** [comment]
> Task :react-native-azure-auth:verifyReleaseResources FAILED
> 
> buildToolsVersion = "31.0.0" minSdkVersion = 21 compileSdkVersion = 31 targetSdkVersion = 31

This is happening for me also in RN 0.70.6. Anybody has some idea?
