### ISSUE TITLE
not working with react native 0.7.x

### ISSUE THREAD

**Issue by cgo123** [vmurin/react-native-azure-auth#170]
by default react native 0.7.x uses react@18. The lib requieres react@"^16.11.0 || ^17"

**Comment by georgetk** [comment]
Hi, I'm open to create a PR for this. But doen't know what to do for supporting RN 0.7x. Could someone guide me in this?

**Comment by vmurin** [comment]
PRs are really appreciated! 🙏🏻

**Comment by vmurin** [comment]
new version supporting react v18 is published to NPM

**Comment by cgo123** [comment]
Thank you very much!!!

**Comment by cgo123** [comment]
Hi @vmurin,

thank you very much for the new version. Unfortunately it does not work for me, I get the following error message:

`npm ERR! Found: react-native@0.70.6
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.70.6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.64.0" from react-native-azure-auth@1.8.6
`

Do you have any ideas?

**Comment by vmurin** [comment]
Sorry, one micro update to 1.8.7 should fix it :)
