### ISSUE TITLE
[Bug] Login fails when multi-factor authentication is active

### ISSUE THREAD

**Issue by oferRounds** [vmurin/react-native-azure-auth#173]
Hi @vmurin 
We got a report from one of our users (on Android Xiaomi), that when multi-factor authentication is turned on, the login fails.
On the video they send we see that after the 2nd verification is done, the app is launched back but nothing happens
I imagine that behind the scenes it launches back but without the acquired token (and other data)

Would you have an idea what might be the issue? I imagine it’s not related to the library itself, and perhaps to the Azure definitions on the client, but just wondered if you might know something

Thank you!
Ofer

**Comment by oferRounds** [comment]
The interesting part is that other users on this company are able to login, and we susspect it might be an issue with Xiaomi as we saw this issue in the past

**Comment by armanbelara** [comment]
Hello @oferRounds, may I know how you implemented the multi-factor authentication using this library? I'm interested to know because we are planning to implement the MFA as well through Azure.

**Comment by oferRounds** [comment]
hey @armanbelara – sorry for my delay!
Actually we haven’t implemented it – I reffered here to this feature which include on Azure – we did nothing on our part

BTW – the issue was solved, it was due to the fact that on our Android manifest the `launchMode` was set to `singleTop` instead of `singleTask`
