### ISSUE TITLE
ID tokens not present

### ISSUE THREAD

**Issue by BB-BenBridges** [vmurin/react-native-azure-auth#174]
Hi

When setting up an `Mobile and Desktop application` in the Azure portal as instructed in the setup, you are not presented with the ID Tokens setting. This is only present when creating a `Web Application`

As a workaround for anyone else who reaches this thread, you can download the JSON manifest, update
```
"oauth2AllowIdTokenImplicitFlow": true,
"oauth2AllowImplicitFlow": true,
```
save, and then upload your updated JSON file.

However, after doing the above, I now get the error `No reply address provided` I have my callback URL set to `authapptest://authapptest/android/callback` for use with the example repo. Where am I going wrong?

**Comment by bb-centrum** [comment]
Fixed by setting the redirect URL in the AzureAuth config:

```
const azureAuth = new AzureAuth({
    clientId: CLIENT_ID,
    tenant: TENNANT,
    redirectUri: 'authapptest://authapptest/android/callback'
  });
```

Doc's should be updated to reflect both of the above issues.

**Comment by shahraizali** [comment]
any luck ?

**Comment by bb-centrum** [comment]
Yes I have the login working however the instructions regarding enabling ID Tokens in the Azure portal are no longer correct. The setting only appears if you select a Web Application type. The only way I can now see to enable this it to download the JSON manifest, update the following
```
"oauth2AllowIdTokenImplicitFlow": true,
"oauth2AllowImplicitFlow": true,
```
save, and then upload your updated JSON file.
