### ISSUE TITLE
/common endpoint is not supported by single tenant apps

### ISSUE THREAD

**Issue by bb-centrum** [vmurin/react-native-azure-auth#175]
Hi! I have just tried testing the example repo with a single tenant app registration and I get the above error.

Manually setting the tenant as per the below fixed this. Can this be added to the docs?

```
const azureAuth = new AzureAuth({
    clientId: CLIENT_ID,
    tenant: 'XXXXXXXX-YYYY-ZZZZ-AAAA-BBBBBBBBBBBB',
  });
```

**Comment by vmurin** [comment]
info added
