### ISSUE TITLE
Is there any way to clearSession without opening the dialog modal ? 

### ISSUE THREAD

**Issue by Nurtilekk** [vmurin/react-native-azure-auth#177]
Is there any way to clearSession without opening the dialog modal ?
<img width="666" alt="image" src="https://user-images.githubusercontent.com/62701301/226335338-3cc1b081-bc7e-4110-bb85-448a17f87111.png">

**Comment by vmurin** [comment]
The session is open on the Azure server, so we should say to Azure to drop it. How to handle this logout process is mostly controlled by server, so it is not possible to logout without dialog
