### ISSUE TITLE
yarn install fails when node_modules and lock files are deleted

### ISSUE THREAD

**Issue by bhishakBitcanny** [vmurin/react-native-azure-auth#180]
<img width="1382" alt="Azure" src="https://github.com/vmurin/react-native-azure-auth/assets/49839906/ebf354ab-ae25-45e3-8016-7bd25ee090cd">

Arguments: 
  /usr/local/bin/node /opt/homebrew/bin/yarn

Yarn version: 
  1.22.19

Node version: 
  16.20.0

Platform: 
  darwin arm64

Trace: 
  Error: https://raw.githubusercontent.com/vmurin/js-base64/4313088c94a7b624d9eece2b7c66df9f697aa264/package.json: ETIMEDOUT
      at Timeout._onTimeout (/opt/homebrew/lib/node_modules/yarn/lib/cli.js:141550:19)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

"react": "18.2.0",
"react-native": "0.71.7",
"react-native-azure-auth": "^1.8.7",

I confirmed by removing this package, there was no network issue.

**Comment by vmurin** [comment]
should be fixed in v1.8.8
