### ISSUE TITLE
Infinite Loading on microsoft login

### ISSUE THREAD

**Issue by MirzaArslan123** [vmurin/react-native-azure-auth#183]
When i enter email for login in microsoft then the app start loading 
![Screenshot 2023-06-08 at 9 56 38 AM](https://github.com/vmurin/react-native-azure-auth/assets/119283732/5cccbb58-6d24-4b3f-bd18-1477e98ccbc4)
![Screenshot 2023-06-08 at 10 00 27 AM](https://github.com/vmurin/react-native-azure-auth/assets/119283732/94c709b9-be93-430b-9c28-75d1dcc6a1ad)
![Screenshot 2023-06-08 at 10 01 01 AM](https://github.com/vmurin/react-native-azure-auth/assets/119283732/2e9300d3-1c3e-4d3d-9cfe-d01af36c2dd4)
![Screenshot 2023-06-08 at 10 01 24 AM](https://github.com/vmurin/react-native-azure-auth/assets/119283732/defaf24b-3fb7-4eb6-b441-d56f1050ee77)
![Screenshot 2023-06-08 at 10 36 11 AM](https://github.com/vmurin/react-native-azure-auth/assets/119283732/36ae10cf-92c2-49c4-8e85-c50439dd15c8)

can anyone help me out

**Comment by vmurin** [comment]
You could check the approaches and thoughts from the issues #27 and #101

**Comment by MirzaArslan123** [comment]
Actually when i type the email and press next then the app not gone to the next password screen

**Comment by vmurin** [comment]
> Actually when i type the email and press next then the app not gone to the next password screen

It should be then definitely some app registration or Azure company account issue. 
Du you have an company or private account? If company, then some additional restrictions are applied. Talk to admins.

**Comment by MirzaArslan123** [comment]
i have a company account can you please explain the additional restrictions

**Comment by vmurin** [comment]
Azure cloud admins from your company can block/restrict some features that could affect login. Unfortunately I did not dig deeper and can not  tell you which particular restrictions could be applied. 
For testing purposes just create a new privat account and try the same app with it.

For now I will close the issue as not related to the library

**Comment by MirzaArslan123** [comment]
ok Thanks
