### ISSUE TITLE
Android build error with latest RN version 0.72.1

### ISSUE THREAD

**Issue by mlazari** [vmurin/react-native-azure-auth#185]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-azure-auth@1.8.8` for the project I'm working on.

After updating my project to the latest version of React Native 0.72.1 I started getting this error on Android:
```
* What went wrong:
Could not determine the dependencies of task ':react-native-azure-auth:bundleLibCompileToJarDebug'.
> Could not create task ':react-native-azure-auth:compileDebugJavaWithJavac'.
   > In order to compile Java 9+ source, please set compileSdkVersion to 30 or above
```
I have this in `android/build.gradle`, but `react-native-azure-auth` is ignoring it and always uses `compileSdkVersion 29`:
```
buildscript {
    ext {
        // ...
        compileSdkVersion = 33
        // ...
    }
    // ...
}
```

Other libraries use the values from `android/build.gradle`, so I did a patch to solve this issue similarly in this library.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-azure-auth/android/build.gradle b/node_modules/react-native-azure-auth/android/build.gradle
index 0814ea0..34c83b7 100644
--- a/node_modules/react-native-azure-auth/android/build.gradle
+++ b/node_modules/react-native-azure-auth/android/build.gradle
@@ -1,7 +1,3 @@
-project.ext {
-    buildToolsVersion = "28.0.3"
-}
-
 buildscript {
     repositories {
         jcenter()
@@ -15,13 +11,17 @@ buildscript {
 
 apply plugin: 'com.android.library'
 
+def safeExtGet(prop, fallback) {
+    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
+}
+
 android {
-    compileSdkVersion 29
-    buildToolsVersion "${project.ext.buildToolsVersion}"
+    compileSdkVersion safeExtGet('compileSdkVersion', 29)
+    buildToolsVersion safeExtGet('buildToolsVersion', '28.0.3')
 
     defaultConfig {
         minSdkVersion 16
-        targetSdkVersion 29
+        targetSdkVersion safeExtGet('targetSdkVersion', 29)
         versionCode 1
         versionName "1.0"
     }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by vmurin** [comment]
Thank you very much for your contribution! 🙏🏻

**Comment by andrei-tectu** [comment]
You are amazing. I used this to fix my e2e test with Detox.
In my case was `minSdkVersion` error so I used it also for

`minSdkVersion safeExtGet('minSdkVersion', 16)`

Thank you

**Comment by DevJoelito** [comment]
Thank you for this!🍻
