### ISSUE TITLE
Cannot complete login on Android

### ISSUE THREAD

**Issue by PMoneda** [vmurin/react-native-azure-auth#19]
Hi, I'am trying to login with AD, so I created my app on azure ad portal, configured all steps following the readme. 
My application is calling back from auth page when I clicked on Accept button or Sign In button but my react native app receives an error like below image.
Could you help me?
My intent filter is just like this:
```xml
<intent-filter>
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.DEFAULT" />
          <category android:name="android.intent.category.BROWSABLE" />
          <data android:pathPrefix="/android/${applicationId}/callback" android:scheme="${applicationId}" />
      </intent-filter>
```
My applicationId on gradle file is like this:
`com.adtest`
On Azure Portal my callback url is like this:
`com.adtest://com.adtest/android/callback`

![image](https://user-images.githubusercontent.com/955433/55490800-c073ff80-560a-11e9-99d4-4a73aadffd22.png)

Best Regards,

**Comment by PMoneda** [comment]
My react native version:
react-native-cli: 2.0.1
react-native: 0.59.3

**Comment by PMoneda** [comment]
I was missing this options on manifest under activity
android:launchMode="singleTask"

Closing this issue

**Comment by vmurin** [comment]
Hey, glad to see that you already solved the problem!
