### ISSUE TITLE
Compile Android problem

### ISSUE THREAD

**Issue by daimonkor** [vmurin/react-native-azure-auth#190]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-azure-auth@1.8.8` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-azure-auth/android/build.gradle b/node_modules/react-native-azure-auth/android/build.gradle
index 0814ea0..3193c3c 100644
--- a/node_modules/react-native-azure-auth/android/build.gradle
+++ b/node_modules/react-native-azure-auth/android/build.gradle
@@ -16,7 +16,7 @@ buildscript {
 apply plugin: 'com.android.library'
 
 android {
-    compileSdkVersion 29
+    compileSdkVersion 30
     buildToolsVersion "${project.ext.buildToolsVersion}"
 
     defaultConfig {
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by vmurin** [comment]
Fixed with PR GH-193
