### ISSUE TITLE
First login attempt always fails

### ISSUE THREAD

**Issue by dev-sda1** [vmurin/react-native-azure-auth#200]
I've built a small application that uses this package following the documentation, however I can only seemingly get authentication to work on the second attempt. The first attempt always results in this being outputted to the console: 
`` [[object Object]: unknown error]``. If I attempt signin again, it'll go through without any problems.

Any idea what's going on? I'm using react-native 0.72.6, and react-native-azure-auth 1.8.9

**Comment by vmurin** [comment]
You can try to build the [sample project](https://github.com/vmurin/react-native-azure-auth-sample) and to check if there any difference.

**Comment by dev-sda1** [comment]
Copied over the code from the sample project and it worked every single time. Decided to copy over the auth section word-for-word into my own screen and now it seems to work every time 😅 No idea what I did different but it seems to work now!

**Comment by vmurin** [comment]
Perfect! :)
