### ISSUE TITLE
Expo Support

### ISSUE THREAD

**Issue by Elue-dev** [vmurin/react-native-azure-auth#201]
Just a question, is this library supported with Expo?

**Comment by vmurin** [comment]
Hi,

please reference to the issues 
https://github.com/vmurin/react-native-azure-auth/issues/87(main)
https://github.com/vmurin/react-native-azure-auth/issues/103 
https://github.com/vmurin/react-native-azure-auth/issues/109

And apparently take a look an [Expo Bare Workflow](https://docs.expo.dev/bare/exploring-bare-workflow/) - it should support native modules, but I don't have any experience with it.
