### ISSUE TITLE
AcquireTokenSilent not working

### ISSUE THREAD

**Issue by elad101** [vmurin/react-native-azure-auth#203]
@vmurin when I called acquireTokenSilent, my tokenExpireDate wasn't extended.
Is it related to the App Reg configuration?
In addition, it was mentioned on other Azure auth packages forceRefresh attribute.
Why don't you support that?

**Comment by vmurin** [comment]
All tokens are cached in the App to optimize network calls. Only if cached token is expired it will be refreshed.
The use cases where someone would need only very new token are not clear for me.
But please feel free to create pull request for force refresh functionality and I'll include it in the library.
