### ISSUE TITLE
[iOS] - Popup name edit

### ISSUE THREAD

**Issue by varshiludani** [vmurin/react-native-azure-auth#204]
Is there a way to control this name being displayed on webAuth.authorise call?

![image](https://github.com/vmurin/react-native-azure-auth/assets/8097579/4b1cfb9d-32bf-4804-9388-e9ef15357651)

I currently also have the following structure in the app.json.

{
  "name": "Appname",
  "displayName": "My cool App Name"
}

Can I change the popup to to use the display name?

Thanks team.

**Comment by varshiludani** [comment]
[SOLVED] - 
The library is using ASWebAuthenticationSession. From iOS 15, looks like you can use CFBundleName to change the name.

**Comment by varshiludani** [comment]
[SOLVED] -
The library is using ASWebAuthenticationSession. From iOS 15, looks like you can use CFBundleName to change the name.

**Comment by vmurin** [comment]
Thank you very much for sharing the solution 🙏🏻❤
