### ISSUE TITLE
Hide the address bar

### ISSUE THREAD

**Issue by Monisankarnath** [vmurin/react-native-azure-auth#207]
Hi @vmurin I am not able to hide the address bar when we try to login using authorize. Is there some way to do that?

**Comment by Monisankarnath** [comment]
@vmurin please help here

**Comment by vmurin** [comment]
I suppose there is no possibility to hide URL navigation bar completely. There is an option to hide it during scroll actions, but that's it.

**Comment by Monisankarnath** [comment]
@vmurin  can we do some changes to add this functionality. The url bar just looks ugly and it has all the details for login showing. It happens during login and logout both.
