### ISSUE TITLE
Not able to change the authorityUrl/issuer using the authorize method

### ISSUE THREAD

**Issue by Monisankarnath** [vmurin/react-native-azure-auth#209]
@vmurin I am tring to use a different authorityUrl or tenant in one case for which I thought I cloud just call the authorize method with the authorityUrl/issuer but that is not working. Can we achieve it in any way?

**Comment by vmurin** [comment]
Please describe current behavior detailed and add a code snippet. With just "not working" is hard to say anything ;)

**Comment by Monisankarnath** [comment]
Ok @vmurin.
So the current behaviour in my app is - 
 - we create the instanceon app init with 
  ```
new AzureAuth({
      clientId: AZURE_AUTH_CLIENT_ID,
    authorityUrl: AZURE_AUTH_AUTHORITY_URL,
    tenant: AZURE_AUTH_TENANT_ID,
      redirectUri: Platform.select(azureAuthConfig.redirectUri),
    })
```

 - Next on Login we call the method 
```
 authorize(scope: azureAuthConfig.scope,
        prompt: "login",)
```
the AZURE_AUTH_AUTHORITY_URL in the above code contains the signin policy tenant.

Now I want to go to create account directly for which I have a separate policy so the authorityUrl will change.
Is there any way to call the authorize method so as to go to the new url?
like - 
```
authorize(
domain: signupUrl,
        scope: azureAuthConfig.scope,
        prompt: "login",
)

```

**Comment by vmurin** [comment]
The library does not support SignUp process. You can only login (sign in) with it. User have to have an account already. 
At the end it's the MS account, not an account of your App.

**Comment by Monisankarnath** [comment]
@vmurin I understand it's the MS account. I just want to change the authorityUrl somehow without creating a new instance. Can we achieve it somehow?

**Comment by Monisankarnath** [comment]
@vmurin I wanted this - 
`url(path, query, authorityUrl) {
        const baseAuthorityUrl = authorityUrl ? `https://${authorityUrl}`: this.baseUrl;
        let endpoint = url.resolve(baseAuthorityUrl, path)
        if (query && query.length !== 0) {
            const parsed = url.parse(endpoint)
            parsed.query = query || {}
            endpoint = url.format(parsed)
        }
        return endpoint
    }
`

**Comment by vmurin** [comment]
I see, but as said - IMHO it's not the use case for the lib

**Comment by Monisankarnath** [comment]
@vmurin  Can we add this feature. react-native-app-auth has it ig

**Comment by vmurin** [comment]
Feel free to create a PR. I will review and merge it.
Don't forget according tests.

**Comment by Monisankarnath** [comment]
sure @vmurin the PR is asking for collaborator priviledges

**Comment by vmurin** [comment]
You should fork this repo, make the changes in it and then create a PR from your repo to this one. There is no any privileges required for this steps.

**Comment by Monisankarnath** [comment]
@vmurin I am getting this error - Holding off the PR until I figure out the solution for this error - invalid_grant: AADB2C90088: The provided grant has not been issued for this endpoint. Actual Value : ________ and Expected Value : ________. 

Actual value  = the policy in the authorityUrl that I am using while instance creation, 
Expected value = the new policy in the authorityUrl sent in the authorize method

Please help trying to find the solution.

Draft PR - https://github.com/vmurin/react-native-azure-auth/pull/211
