### ISSUE TITLE
Data dog Rum is supported react native web ?

### ISSUE THREAD

**Issue by melbythomas** [vmurin/react-native-azure-auth#210]
I need to integrate Datadog Rum for my react native web project am trying to add but am getting error."WARNING in ../../node_modules/@datadog/mobile-react-native/lib/module/specs/NativeDdLogs.js 13:15-38
export 'TurboModuleRegistry' (imported as 'TurboModuleRegistry') was not found in 'react-native' (possible exports: AccessibilityInfo, ActivityIndicator, Alert, Animated, AppRegistry, AppState, Appearance, BackHandler, Button, CheckBox, Clipboard, DeviceEventEmitter, Dimensions, Easing, FlatList, I18nManager, Image, ImageBackground, InteractionManager, Keyboard, KeyboardAvoidingView, LayoutAnimation, Linking, LogBox, Modal, NativeEventEmitter, NativeModules, PanResponder, Picker, PixelRatio, Platform, Pressable, ProgressBar, RefreshControl, SafeAreaView, ScrollView, SectionList, Share, StatusBar, StyleSheet, Switch, Text, TextInput, Touchable, TouchableHighlight, TouchableNativeFeedback, TouchableOpacity, TouchableWithoutFeedback, UIManager, Vibration, View, VirtualizedList, YellowBox, findNodeHandle, processColor, render, unmountComponentAtNode, unstable_createElement, useColorScheme, useLocaleContext, useWindowDimensions)" Datadog is supported in react native web ? am refering this https://github.com/DataDog/dd-sdk-reactnative  @louiszawadzki @xgouchet @0xnm  Am using  "react-native": "0.72.3", this version

**Comment by vmurin** [comment]
what does this have to do with this lib?
