### ISSUE TITLE
android stuck on "continue", does nothing

### ISSUE THREAD

**Issue by jliukai** [vmurin/react-native-azure-auth#216]
# Problem

When I attempt to sign in, and press "continue" it does nothing. 

![tBUI3](https://github.com/vmurin/react-native-azure-auth/assets/9878800/33ce5975-a534-4f39-9785-c301e0844a90)

# Setup
- android physical device, React native Firebase.
- iOS, Microsoft Sign in works fine with react-native-azure-auth lib.
- code client id and redirect sources
     - client id is from the entra > app registration > overview > app client id
     - redirect uri is from entra > app registration > authentication > android card > redirect uri.
            - redirect uri looks something like msauth://com.myappname.dev/FAaX%2123454lc2OAabcdedgh6s%3D 
               ![9otMo](https://github.com/vmurin/react-native-azure-auth/assets/9878800/7cf7b7aa-c6ac-4a3a-95af-e651c9154de4)
- made sure the package name matches my app package name.
- in the Entra auth page,
   - ID tokens (used for implicit and hybrid flows) and Access tokens (used for implicit flows) are checked.
   - Allow public client flows set to yes.
 - In firebase auth page, added my client id and secret to that microsoft sign in section. client id and secret are from entra app registrations.
 
 ```
// my code
import AzureAuth from 'react-native-azure-auth' // 1.8.9

const azureAuth = new AzureAuth({
  clientId: Config.MICROSOFT_CLIENT_ID,
  redirectUri: Config.MICROSOFT_REDIRECT_URI_ANDROID
})

const tokens = await azureAuth.webAuth.authorize({
   scope: 'email openid profile User.Read offline_access',
   prompt: 'select_account'
})
console.log('tokens') // <--- never gets to here
```

**Comment by vmurin** [comment]
Please check the issue #27 and give your feedback here 🙏🏻

**Comment by qwert251102** [comment]
same @vmurin  issue for me i have checked #27 
here is the intent filter
<intent-filter android:label="redirect">
           <action android:name="android.intent.action.VIEW" />
           <category android:name="android.intent.category.DEFAULT" />
           <category android:name="android.intent.category.BROWSABLE" />
           <data
              android:scheme="msauth"
              android:host="package-name"
              android:pathPrefix="/signature-hash"
             />
       </intent-filter>
in place of package-name i have used my real package name 
in place of signature-hash i have used my signature-hash

**Comment by qwert251102** [comment]
same @vmurin issue for me i have checked https://github.com/vmurin/react-native-azure-auth/issues/27
here is the intent filter`<intent-filter android:label="redirect">
           <action android:name="android.intent.action.VIEW" />
           <category android:name="android.intent.category.DEFAULT" />
           <category android:name="android.intent.category.BROWSABLE" />
           <data
              android:scheme="msauth"
              android:host="package-name"
              android:pathPrefix="/signature-hash"
             />
       </intent-filter>` in place of package-name i have used my real package name 
in place of signature-hash i have used my signature-hash

**Comment by jliukai** [comment]
i added the section to Androidmanifest.xml

```
# Androidmanifest.xml
 <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data
              android:pathPrefix="/android/callback"
              android:host="${applicationId}"
              android:scheme="${applicationId}" 
            />
            <!-- added this part -->
            <data            
              android:scheme="msauth" 
              android:host="com.<my package name>" 
              android:pathPrefix="/<my hash>" 
            />
            <!-- end add this part -->
        </intent-filter>
 ```
 
 ```
// react native code
 const azureAuth = new AzureAuth({ clientId, redirectUri })
    const tokens = await azureAuth.webAuth.authorize({
      scope: 'email openid profile User.Read offline_access',
      prompt: 'select_account'
    })
```

 
### how i created my hash
1. i tried both development via using debug.keystore and  production from the google play store downloading `deployment_cert.der`
2.  from a mac, ie. using cli command: `keytool -exportcert -alias androiddebugkey -keystore debug.keystore | openssl sha1 -binary | openssl base64`  to generate the hash
3. taking the  hash in to get redirect uri
    - MS entra website > app registrations > and in the android section -> to get the redirect uri.
4. 
    - putting hash in androidmanifest, as seen above.
    - and redirecturi  my react native code  seen above.

I still have problem where "continue" button doesnt do anything. im sure its something wrong with redirect url or some config around that.

**Comment by vmurin** [comment]
Hi @jliukai 

please try following:

1. remove android as a Platform from the App registration. It is actually enough to have "Mobile and Desktop applications"
2a. Use you the variant 4 but double check the URL spelling 
2b. Or Use the variant as in the documentation

```xml
  android:pathPrefix="/android/callback"
  android:host="com..prod"
  android:scheme="com..prod" 
```
here supposed "com..prod" is your package name and it is correctly put in the Azure App registration as the callback URI

3. please check the value of the  `redirectUri ` variable in the code `const azureAuth = new AzureAuth({ clientId, redirectUri })`
It should be exactly copy-pasted from Azure URIs list

_The main rule:_
App registration callback URI === redirectUri variable === **android:scheme** + :// + **android:host** + **android:pathPrefix**

**Comment by jliukai** [comment]
it worked!! thank you thank you!!!

- removed android section in Entra app registration.
-  redirect URI in new AzureAuth is com.<myapp.prod>://com.<myapp.prod>/android/callback
- and the original instructed code in android manifest worked.

```
 <data
              android:pathPrefix="/android/callback"
              android:host="${applicationId}"
              android:scheme="${applicationId}" 
            />
```

**Comment by vmurin** [comment]
@jliukai thank you for your feedback
