### ISSUE TITLE
[Error: Not a valid base64 encoded string length]

### ISSUE THREAD

**Issue by sarth-in** [vmurin/react-native-azure-auth#219]
After doing first time login, getting error base64 encoded string length.
not able to generate new token

**Comment by Ankur5522** [comment]
I am facing the same issue, though i am not able to solve it yet completely but i find that deleting the data of the app and trying logging it again helps in fetching the token again. So, i guess the token is being stored on the device.

**Comment by sarth-in** [comment]
@Ankur5522 yeah, i tried that approach also, after uninstalling the app it works fine for first time but after sometime i need to call acquireTokenSilent, in that case also i am getting this same error

**Comment by Ankur5522** [comment]
You can create a logout function and call await `await azureAuth.auth.clearPersistenCache();` function in it. It would work.

**Comment by sarth-in** [comment]
@Ankur5522 this approach worked, Thanks
but i need to call acquireTokenSilent method for refreshing the access_token

**Comment by Ankur5522** [comment]
Good to know it worked out.

**Comment by Prabhat2510** [comment]
You need to poly-fill atob function using something like core-js or base-64 like this -
1. 
import "core-js/stable/atob";
import { jwtDecode } from "jwt-decode";

const token = "eyJ0eXAiO.../// jwt token";
const decoded = jwtDecode(token);

console.log(decoded);

2.
import { decode } from "base-64";

global.atob = decode;

For more insights see this - https://stackoverflow.com/a/77481496

**Comment by tranminhnhat1005** [comment]
I think at the moment you can set the version of react-native-azure-auth to 1.8.9 by removing the caret:

`"react-native-azure-auth": "1.8.9"`

I tried and it work for me.
