### ISSUE TITLE
Invalid token specified

### ISSUE THREAD

**Issue by sarth-in** [vmurin/react-native-azure-auth#222]
[InvalidTokenError: Invalid token specified: invalid base64 for part #2 (Maximum call stack size exceeded (native stack depth))]
getting this error in iOS and android both

**Comment by mitalpatelOG** [comment]
I am also getting same error. Any one get the solution ?

**Comment by mattshapiro** [comment]
Seeing the same. Seemed to pop up when we upgraded from Expo 50 / RN 0.73 -> Expo 51 / RN 0.74.

**Comment by mattshapiro** [comment]
I _think_ I found a temp workaround for this. In react-native-azure-auth/src/token/token.js line 10 I replaced "js-base64" with "base-64" and added "base-64" to my devDependencies in package.json.

from...
`import { decode } from 'js-base64'`

to...
`import { decode } from 'base-64'`

**Comment by DanStorm** [comment]
Same issue after upgrade to RN 0.74 (not expo)

@mattshapiro's solution works

**Comment by vmurin** [comment]
Fixed. Thanks @mattshapiro
