### ISSUE TITLE
Persistent storage cannot be disabled

### ISSUE THREAD

**Issue by christianfroehlich** [vmurin/react-native-azure-auth#226]
Hi,
I'm trying to configure the auth to not store the token persistently to optimise the security practices of my app.

I have it configured as below, however the token is still saved to `AsyncStorage`

```
private static azureAuth: AzureAuth = new AzureAuth({
    clientId: Config.AZURE_AD_CLIENT_ID,
    tenant: Config.AZURE_AD_TENANT_ID,    
    persistentCache: 'false',
  });
```

Looking at the code this appears to be a bug firstly as the parameter is mapped as a string in the [typing](https://github.com/vmurin/react-native-azure-auth/blob/fbccd8e1e0d90f9fc0e061abfce539b0534c4632/types/index.d.ts#L11), e.g.

```
interface AzureAuthOptions {
  /** @param {String} clientId your AzureAuth client identifier */
  clientId: string;
  /** @param {boolean} [persistentCache] should store token cache between the app starts; defaults to true */
  persistentCache?: string;
```

and secondly because in [cache.js](https://github.com/vmurin/react-native-azure-auth/blob/fbccd8e1e0d90f9fc0e061abfce539b0534c4632/src/token/cache.js#L38) the value will always be defaulted to true as there is no value that could be more truthy than `true`, e.g.
```this.persistent = params.persistent || true // by default enabled```

i.e. this will equal `"false"`, and when later compared with `if ("false")` this will always evaluate to true. 
Also even if the typing was correct `false || true` will always be evaluated as `true`.

It seems like a simple fix and happy to submit a PR if you'd like.

**Comment by vmurin** [comment]
Hi,  thank you for your message. It looks for me as a bug as well . 
It would be nice If you would provide a PR.
Dont forger a Default :)

**Comment by vmurin** [comment]
Fixed with PR #227

**Comment by christianfroehlich** [comment]
Hi @vmurin, thank you for allowing me to contribute, i do appreciate the prompt response too!

I hope i'm not jumping the gun by asking, but assuming there aren't any issues, would it be possible to have this released?

**Comment by christianfroehlich** [comment]
Please disregard my prior message, i was mistaken. Thank you for accepting my contribution and your really quick response!
