### ISSUE TITLE
yellowbox warning: Module AzureAuth requires main queue setup since it overrides `constantsToExport`

### ISSUE THREAD

**Issue by robertvorthman** [vmurin/react-native-azure-auth#25]
When I create a new AzureAuth object I see the following yellowbox warning, although it doesn't seem to be a problem for now.

> Module AzureAuth requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

**Comment by vmurin** [comment]
The issue will be handled in the opened pull request #23
