### ISSUE TITLE
No return to application after redirect

### ISSUE THREAD

**Issue by VadimCeretean** [vmurin/react-native-azure-auth#27]
После прохождения аутентификации webView переходит по redirectUri и не возвращает в приложение, что может быть не так?

**Comment by vmurin** [comment]
Please describe the problem more detailed. What are your actions, what do you see on the screen, what ist the expected behavior and what you get instead.

**Comment by VadimCeretean** [comment]
I set same redirect url in azure and in the app, but after login webview redirect to blank page and don't  redirect to app

**Comment by VadimCeretean** [comment]
I press log in, enter to account and aftert browser show me blank page

**Comment by vmurin** [comment]
Thank you for the input!
Following additional data needed to analyse the issue:
1. What OS you are on?
2. What is your call back URI registered in MS App Registration or Azure portal? 
3. In which section of registration portal you entered  the callback URI? (Web or Desktop+devices or Native in the old portal UI)
4. Attach your `AndroidManifest.xml` or iOS `Info.plist` 

Best regards
V.

**Comment by VadimCeretean** [comment]
1. Windows 
 2. a) msal121b9b31-6df5-4560-857b-f2485ba13ba4://auth 
     is return 
![zs3ZlHDs](https://user-images.githubusercontent.com/45070098/60340365-ce94aa80-99c4-11e9-975a-643305491c25.png)

     b)https://login.microsoftonline.com/common/oauth2/nativeclient
     is return 
![Screenshot_6](https://user-images.githubusercontent.com/45070098/60340441-000d7600-99c5-11e9-85b4-a720efee7a82.png)

3. 
![P9za2RY8](https://user-images.githubusercontent.com/45070098/60340318-a311c000-99c4-11e9-8cf0-f2638d4e8edf.png)
4.  
![Xv2wrKf9](https://user-images.githubusercontent.com/45070098/60340521-419e2100-99c5-11e9-97ac-7bf507a024ca.png)

Thank You for help!

**Comment by vmurin** [comment]
Hey Vadim,

it seems one `intent-filter` in your manifest is missing.
Compare the example from readme with you file: https://github.com/vmurin/react-native-azure-auth#app-configuration

The data section with `android:scheme` should be in another filter (it has VIEW in it). 
Try to correct the manifest and tell me if it works.

**Comment by VadimCeretean** [comment]
I correct my manifest, but it still not work
![3tDqy2ru](https://user-images.githubusercontent.com/45070098/60381176-ec681b00-9a69-11e9-96be-335b325305a8.png)

**Comment by VadimCeretean** [comment]
Hi! i changed manifest like this and now it's work! Thank You!
![38512247d1](https://user-images.githubusercontent.com/45070098/60382921-b33ca480-9a83-11e9-83c3-2d3013d4c666.jpg)

**Comment by vmurin** [comment]
Perfect! Good news.
I see you have used the generated URI from MS portal. It is a valid approach too.
Actually the only important thing is the correct spelling. You should have the same URI in the portal and manifest. In the previous variant without `android:host` key the key "android:prefix" is ignored, so every request with given scheme `com.stenn` would be redirect to the app. I suppose it was somewhere misspelled ... for example with extra space character or some Cyrillic character (e.g. `c` ???) in the manifest or portal. 
Another consideration - may be you have some another app using the same scheme. In this case the additional data key `android:host` helps to identify the correct one.
So I'll now close the issue.
Good luck!

Relevant docs:
https://developer.android.com/training/app-links/deep-linking#adding-filters
https://developer.android.com/guide/topics/manifest/data-element

**Comment by gustavohcastro** [comment]
Hi,
I have the same problem in Android, iOS works fine, but it Android after a press continue or cancel both anything happens...
Someone can help me?

**Comment by vmurin** [comment]
Hi Gustavo,
did you check/compare the spelling of the android:scheme in the android manifest and redirect URL in App registration - this is the only what could be wrong

**Comment by gustavohcastro** [comment]
> 

Hi vmurin,

I found a solution, in azure portal when i put the signature hash, azure portal encode base64, so its different than I was put in AndroidManifest.xml

Thanks

**Comment by vmurin** [comment]
thanks for your feedback!
