### ISSUE TITLE
App Registration instructions may need updating

### ISSUE THREAD

**Issue by internetstaff** [vmurin/react-native-azure-auth#28]
I'm trying to complete the callback URL registration and failing miserably. :)

In the Microsoft Application Registration Portal, if I put in an Android callback URL per the instructions, I always get "Your changes could not be saved.
One or more added object references already exist for the following modified properties: 'owners'."

If I try any other test URL, I get simply "Your changes could not be saved." and no error details.

Since the MAR portal has a "no longer supported after May 2019" warning at the top, I'm wondering if it's broken / dead.

If I try the new Azure portal and try to enter an Android callback under "Redirect URIs" and then "Public client (mobile & desktop)", the field turns red and it won't allow it to save.

I could be doing something wrong, but I'm wondering if there may be updated instructions.

Thanks!

**Comment by vmurin** [comment]
Hi,

please post here the examples of your callback URIs, that are not accepted by MS registration or Azure portal, together with error messages .

**Comment by internetstaff** [comment]
my applicationId and package are both "com.possible_mobile"

Per the guidelines, `{YOUR_APP_PACKAGE_NAME}://{YOUR_APP_PACKAGE_NAME}/android/callback
`, I used `com.possible_mobile://com.possible_mobile/android/callback`

The old console accepts the URI,  but returns:

![image](https://user-images.githubusercontent.com/1239118/60304086-265fe280-98ed-11e9-8545-588cc1d5ee3c.png)


In the new Azure App Registration console, the input box turns red with no useful error message displayed. 

![image](https://user-images.githubusercontent.com/1239118/60304338-0381fe00-98ee-11e9-9803-c324e397dfb7.png)

**Comment by vmurin** [comment]
According to RFC 2396 (Section 3.1) :

`scheme    =  alpha *( alpha | digit | "+" | "-" | "." )`

So the underscore character in your package name is invalid in this case. Also I found that for some not understandable reason Azure don't like underscore in the another parts of URI too. 
If you replace/remove '_' all will work in both - the App Registration and Azure portals.

And I will update readme with new information. :)
Thank you for helping pointing this out!

**Comment by internetstaff** [comment]
Thanks for looking at this!

FWIW, their portal updated and now it displays useful errors about the URL. It appears to be just the scheme that is a problem, but yesterday even FQDNs with https were randomly failing.

Both portals now seem to work fine.
