### ISSUE TITLE
Logout and login as another user

### ISSUE THREAD

**Issue by VadimCeretean** [vmurin/react-native-azure-auth#32]
Can you show example code how to logout from Azure, not only removing token from AsyncStorage?

**Comment by vmurin** [comment]
Hi Vadim

Sorry for a long silence - I was on my vacation and was not able to answer :)
I have just updated the clearSession method in WebAuth (check out the version 1.1.4). Now it should work on both iOS and Android and call Azure logout URL
Let me know if you still have the problem

Best regards
Vladi

**Comment by vivekspraxa** [comment]
@vmurin it is not available on npm

**Comment by vmurin** [comment]
Just pushed to npm. Thanks @vivekspraxa  :)
