### ISSUE TITLE
B2C integration

### ISSUE THREAD

**Issue by paomosca** [vmurin/react-native-azure-auth#34]
There is a way to add params to autorizeUrl like "p=B2C_1_SIGN" to support B2C AD auth?

**Comment by vmurin** [comment]
Hi,

you can add any additional parameters in authorize call.
See this line in the [sample app](https://github.com/vmurin/react-native-azure-auth-sample) - with your param it will look like this:

```javascript
let tokens = await azureAuth.webAuth.authorize({scope: 'openid profile User.Read', p: 'B2C_1_SIGN' })
```

**Comment by c0d3blooded** [comment]
Another note as I needed a little bit more to get my setup working. You can change the `authorityUrl` in the AzureAuth object to something like:
`https://xxxxx.b2clogin.com/te/{tenant}/{policy}/oauth2/v2.0/`
if you're getting a 404

Ended up finding this after digging around
https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/active-directory-b2c/oauth2-technical-profile.md
