### ISSUE TITLE
User session not clear/logout in IOS

### ISSUE THREAD

**Issue by dkrockcom** [vmurin/react-native-azure-auth#35]
Hi Vmurin,

I have use this plugin for SSO with Microsoft IdToken.
When I logout using 

> azureAuth.webAuth.clearSession({})

 get the success callback.

When I got to login, then app is auto login with older account, it should be take credentials for other account.

**Login Code Sample**
```
 util.auth.webAuth.authorize({ scope: 'openid profile User.Read' }).then((resp) => {
          storage.token.saveToken(resp.rawIdToken, (saved) => {
            if (saved) {
              me.props.dispatch(loginAction.request({ HTTP_X_MS_TOKEN_GOOGLE_ID_TOKEN: resp.rawIdToken }));
            } else {
              util.alert({ title: 'Error', message: 'Token Not saved' });
              this.props.dispatch(loading({ isLoad: false }));
            }
          });
        }, (err) => {
          this.props.dispatch(loading({ isLoad: false }));
          util.alert({ title: 'Error', message: err.error_description });
        });
      })
```

**Logout Code Sample**

```
    util.auth.webAuth.logout({}).then((resp) => {
      util.navigation.navigate('Login');
    });
```

**Custom Util**

```
import AzureAuth from 'react-native-azure-auth';
import consts from './consts';

let util = {
auth: new AzureAuth({
        clientId: consts.AzureConfig.client_id,
        persistentCache: false
    })
}
export default util;
```

Thanks,
Devesh

**Comment by vmurin** [comment]
Check the similar issue #32  - I have just updated NMP package. Before this the change was only committed on guthub. Try now to update to v.1.1.4
It should work on iOS too.

Please reopen the issue if you still have the problem

**Comment by oferRounds** [comment]
Ok, will do – thanks!
Also, I think I noticed an error on this line: https://github.com/vmurin/react-native-azure-auth/blob/640c62b53c6f3b9c849a8f5f5b276a4c740444ad/src/auth/index.js#L247

Should be: `this.cache.removeToken`
