### ISSUE TITLE
Not close window after logout

### ISSUE THREAD

**Issue by vuongductuanktmt** [vmurin/react-native-azure-auth#37]
I used `azureAuth.webAuth.clearSession({})` but on android not close window after logout
![Screenshot_1569780445](https://user-images.githubusercontent.com/25997663/65837314-f24af200-e31f-11e9-8137-8455fb097819.png)

Please help me! :(

**Comment by vmurin** [comment]
Please check the comment to issue #36 and check if it help in your case

**Comment by vuongductuanktmt** [comment]
> Please check the comment to issue #36 and check if it help in your case
I using latest version "react-native-azure-auth": "^1.1.5" but not working

**Comment by vmurin** [comment]
Hi,

please upgrade to v1.2 for better android logout support. Now the callback of `clearSession()` method is called correctly if you manually close the Azure logout window (from your screenshot). 
See [sample application](https://github.com/vmurin/react-native-azure-auth-sample)

The same behavior as on iOS is though impossible as android lacks the browser intent onLoad event.
