### ISSUE TITLE
After Login Redirect to Dashboard

### ISSUE THREAD

**Issue by manpreetsingh3215** [vmurin/react-native-azure-auth#39]
The library is working fine. The problem is when I came back after login is successful it does not navigate to Dashboard screen. This is my code:
```
async azureLogin(){
    try {
      let tokens = await azureAuth.webAuth.authorize({scope: 'openid profile User.Read Mail.Read' })
      this.setState({ accessToken: tokens.accessToken });
      let info = await azureAuth.auth.msGraphRequest({token: tokens.accessToken, path: '/me'})
      this.setState({ user: info.displayName, userId: tokens.userId },()=>{
        this.props.navigation.navigate('Dashboard'); 
      })
      
    } catch (error) {
      console.log(error)
    }
  }
```

**Comment by vmurin** [comment]
I suppose you have some problem with navigation prop in the callback.
Add debug logging into `setState` callback and check the `this.props.navigation` value.
Probably you did not call  `super(props)` in component constructor... or something else.

Much better place to ask the questions like yours is the https://stackoverflow.com/questions

Good Luck!
