### ISSUE TITLE
Android issue after auth

### ISSUE THREAD

**Issue by Aleksandern** [vmurin/react-native-azure-auth#4]
Hello
On Android 26 after success authtorization the opened brawser is trying to open the next url with parameters
com.name://com.name/android/callback#params
So it doesn't open my app.
How can I fix it?

**Comment by vmurin** [comment]
Hi Alex,

the callback URL is defined only by you in the Azure Cloud during the App registration process (see readme).
Your app should be also configured accordingly to react on callback URL and be opened - for this also see readme part "App configuration". "configured accordingly" means: the app configuration should use the same values used to construct the callback URL maintained for the app by registering.

Kind regards
Vladimir
