### ISSUE TITLE
Sigining in with react-native-azure-auth

### ISSUE THREAD

**Issue by ONaggar** [vmurin/react-native-azure-auth#40]
I followed the setup instructions and I'm getting this error 

[invalid_grant: AADSTS70000: The provided 'code_verifier' input value does not match the original 'code_challenge.'
Trace ID: 6188a23a-6f74-4b98-a788-7f1928469100
Correlation ID: cd809842-ffbb-4d42-a358-d8c20923b8c8
Timestamp: 2019-10-15 20:21:16Z]

ReactNative: 0.61.2
react-native-azure-auth: 1.2.0

**Comment by vmurin** [comment]
Thank you very much for reporting this bug!
The bugfixed version 1.2.1 is published.
Please update and feel free to reopen the issue if the problem persists.

**Comment by ONaggar** [comment]
The problem still occurs after moving to version 1.2.1

**Comment by vmurin** [comment]
Please delete `node_modules`, rebuild your app and check again. I rechecked the functionality with [sample app](https://github.com/vmurin/react-native-azure-auth-sample) and it works as intended.
