### ISSUE TITLE
Issue with account type supported by app

### ISSUE THREAD

**Issue by CelsoTeixeira** [vmurin/react-native-azure-auth#42]
Hello, im having a issue with the account type that should be supported by the app.
If I choose for accounts only in this directory, I receive a error when opening the web auth with the unauthorized_client.

Is there a solution/configuration that I should be using that limits the access to only the aplication im registering and not opening to all azure ad?

**Comment by vmurin** [comment]
1) Are you using Azure portal for App registration?
2) Please post here the portion of your app manifest with `signInAudience` , `accessTokenAcceptedVersion` values
3) When you get the error message? Describe steps.
4) What type of the Microsoft account you are using? Do you have additional account where you could have cached (in browser view) login tokens?

**Comment by vmurin** [comment]
Issue closed due to missing input
