### ISSUE TITLE
How to configure MSAL identifier in ios

### ISSUE THREAD

**Issue by suresh777** [vmurin/react-native-azure-auth#43]
Earlier i have used react native msal plugin there i configured with msal identifier. Here if i give my msal identifier in url schemes it is not working.

```
<key>CFBundleURLTypes</key>
<array>
	<dict>
		<key>CFBundleTypeRole</key>
		<string>Editor</string>
		<key>CFBundleURLName</key>
		<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
		<key>CFBundleURLSchemes</key>
		<array>
			<string>msalXXXXXXXXXXXXXXXXXXXXX</string>
		</array>
	</dict>
</array>
```

I am getting this error

Application is not configured as a multi-tenant application.Usage of the /common endpoint is not supported for such applications created after 10/15/2018 use a tenant specific endpoint or configure the application to be multi-tenant

**Comment by vmurin** [comment]
At first - just follow the instructions in README. The app registration steps and the callback URI structure are described there.

In you case I suppose you have to either change the app registration to multi-tenant or use additional parameters by library initialization (AzureAuth constructor) - see the [docs](https://vmurin.github.io/react-native-azure-auth/AzureAuth.html)

**Comment by toxicsebastian** [comment]
I had a similar problem, at least getting the same error in my react native implementation. However adding my tenant ID found in azure to the client init in my code fixed it.

`const azureAuth = new AzureAuth({
  clientId: 'yy',
  tenant: 'xx'
});
`
