### ISSUE TITLE
Missing required parameter in silent token

### ISSUE THREAD

**Issue by suresh777** [vmurin/react-native-azure-auth#44]
I am using this plugin for login, i am calling silent login with valid parameters still i am getting this issue
```
 try {
            // Try to get cached token or refresh an expired ones
            let token = await azureAuth.auth.acquireTokenSilent({userId: tokenUserId,scope: customscope})
            if (!token) {
                // No cached tokens or the requested scope defines new not yet consented permissions
                // Open a window for user interaction
                token = await azureAuth.webAuth.authorize({scope: customscope})
                return token
            }
            return token
        } catch (error) {
            console.log(error)
            return error
        }

```
console.error: "Error in silent request: ", Missing required parameters: Missing required parameters: [
  "refresh_token"
]

Auth#acquireTokenSilent
    index.js:199:20
tryCatch
    runtime.js:45:39
invoke
    runtime.js:271:21
prototype.method
    runtime.js:97:20
tryCatch
    runtime.js:45:39
invoke
    runtime.js:135:19
Promise.resolve.then$argument_0
    runtime.js:145:12
tryCallOne
    core.js:37:11

**Comment by vmurin** [comment]
For some reason you have some broken or empty refresh token in your AsyncStorage. 
I have just updated the `getRefreshToken` method to handle this issue.
Please update the library to 1.2.2 and try again

**Comment by suresh777** [comment]
Now i am not getting refresh token error but in silent login it is again asking login ,means silent login is failing.
I am sending my custom parameters in options:
const options = {
    clientId: ‘XXXXXXXXXXXXXXXXXXXXXXXXXXXX’,
    tenant: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXX’',
    redirectUri: 'msalXXXXXXXXXXXXXXXXXXXXXXXXXXXX’://auth',
    persistentCache:true,
    authorityUrl:'https://login.microsoftonline.com/4XXXXXXXXXXXXXXXXXXXXXXXXXXXX’/oauth2/v2.0/'
}
const azureAuth = new AzureAuth(options);
