### ISSUE TITLE
AcquireTokenSilent not working

### ISSUE THREAD

**Issue by suresh777** [vmurin/react-native-azure-auth#45]
I am getting response after successful login after that i am killing my app and try to do silent login it is navigating to user interaction login. Am i doing anything wrong 
code:

```
import AzureAuth from 'react-native-azure-auth';

const options = {
    clientId: ‘XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX’,
    tenant: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    redirectUri: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX’://auth',
    persistentCache:true,
    authorityUrl:'https://login.microsoftonline.com/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX’/oauth2/v2.0/'
}
const azureAuth = new AzureAuth(options);
const custom_scope =["XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX’"];


class AzureAuthLogin {

    static getToken = async() => {
        try {
            let token = await azureAuth.webAuth.authorize({scope: custom_scope[0]})
            return token
        } catch (error) {
            console.log(error)
            return error
        }
    }
    static getSilentToken = async (tokenUserId) => {
        try {
            // Try to get cached token or refresh an expired ones
            let token = await azureAuth.auth.acquireTokenSilent({ userId: tokenUserId,scope: custom_scope[0]})
            if (!token) {
                // No cached tokens or the requested scope defines new not yet consented permissions
                // Open a window for user interaction
                token = await azureAuth.webAuth.authorize({scope: custom_scope[0]})
                return token
            }
            return token
        } catch (error) {
            console.log(error)
            return error
        }
    }

    
}

export default AzureAuthLogin;
```

**Comment by vmurin** [comment]
The code is truly OK. But I don't see the calls of this methods. Probably you always call `getToken` before `getSilentToken`
By the way - the cache is persistent by default.

Did you check the API access with obtained access token? Possibly you do not get the right token at all? Some app registration issues could be the reason. 

Are you on android or iOS? I can check only android version and the persistent cache in the sample app works as intended.  The `AsyncStorage` is actually cross platform feature of RN, but theoretically it could have some iOS issues.

Please check all the points above and come back with report :)

**Comment by vmurin** [comment]
I suppose you encountered some AsyncStorage issue. Are you on the last RN version?

Please check related github issues and solutions proposed there. 
For example:
https://github.com/react-native-community/async-storage/issues/158
https://github.com/react-native-community/async-storage/issues/89

Actually you can test AsyncStorage independent from AzureAuth library. Try to instantiate AS and save and retrieve some value.

**Comment by suresh777** [comment]
Yes i am using react native latest version
Ok i will check async storage

**Comment by vmurin** [comment]
You did not listed refresh token in your response. It should be there. The scope `offline_access` needed to get refresh token is always added automatically. If you did not get it - something goes wrong. Probably you app registration has some restrictions...

**Comment by suresh777** [comment]
I debugged Azure auth class, In my response refresh token is there will it cause any problem

**Comment by vmurin** [comment]
> I debugged Azure auth class, In my response refresh token is there will it cause any problem

OK. It should be there, so here is everything right! ;)

**Comment by vmurin** [comment]
Hi, 

in the issue #46  you wrote 
>  working fine in ios

Does it mean you have now solved this cache issue?
Please update the issue tracker with your solution or found bug.

**Comment by suresh777** [comment]
Due to our company policy in azure  it is asking again login

**Comment by elad101** [comment]
@vmurin when I called acquireTokenSilent, my tokenExpireDate wasn't extended.
Is it related to the App Reg configuration?
In addition, it was mentioned on other Azure auth packages forceRefresh attribute.
Why don't you support that?

**Comment by Monisankarnath** [comment]
Hi @vmurin, I am facing the same issue. If I try to login using **webAuth.authorize** I am able to login by adding the email and password in the b2c login and get the response, after that if I try to login using **auth.acquireTokenSilent** I get an error - **[TypeError: Cannot read property 'accessToken' of null]**. Now, if I try **webAuth.authorize** again I dont need to add email and password and it directly allows me to login.
Package versions -
 - "@react-native-async-storage/async-storage": "^1.21.0", // auto linked if I import AsyncStorage, tested separately working as expected
 - "react-native-azure-auth": "^1.8.9",
I am facing this issue in ios for now. Didn't test it in android. Please help me here.
