### ISSUE TITLE
ios Bundle Identifier in Custom URI

### ISSUE THREAD

**Issue by ohtoritoritori** [vmurin/react-native-azure-auth#5]
I'm following along with your tutorial. I am curious if something has changed to the uri callback formation ({YOUR_BUNDLE_IDENTIFIER}://${YOUR_BUNDLE_IDENTIFIER}/ios/callback)? I'm trying to save a new custom uri after adding Platforms/Native Device and it won't let me save. I remove it and I can save - with no real warning as to why. New to react-native. Thanks for helping. -Tori

**Comment by vmurin** [comment]
It has nothing to do with react-native but with error handling by MS app portal. There is sadly no understandable error message there.
My suggestion - could it be, that you enter the URI as written in README without expanding the variable YOUR_BUNDLE_IDENTIFIER.
The part ${YOUR_BUNDLE_IDENTIFIER} should be replaced with your actual source code bundle ID.
Check for example this article about bundle ID: https://cocoacasts.com/what-are-app-ids-and-bundle-identifiers/ or just google for it. 
BTW: You you must not use any parenthesis and uppercase characters in URI

**Comment by ohtoritoritori** [comment]
It is obvious that your bundle identifier needs to replace {}. You get your bundle id from Xcode correct? I’ve read on a few other sites that maybe it needs to be 1st your scheme and then your bundle id. This is mine: org.reactjs.native.example.cda-mobile-practice-2. 

{YOUR_BUNDLE_IDENTIFIER}://${YOUR_BUNDLE_IDENTIFIER}/ios/callback

**Comment by ohtoritoritori** [comment]
org.reactjs.native.example.cda-mobile-practice-2://$org.reactjs.native.example.cda-mobile-practice-2/ios/callback

This doesn’t work. Is there something wrong with the syntax? Thanks for the help. -Tori

**Comment by vmurin** [comment]
1) "it needs to be 1st your scheme" - correct. In this case the scheme ist the bundle id - it is also OK as it is only a convention. Just the same scheme should be in the App config (see section https://github.com/vmurin/react-native-azure-auth#ios-config - we are registering new scheme here **CFBundleURLSchemes**) and Azure app registration - then it should work. 
2) try to remove dollar sign from URL

**Comment by ohtoritoritori** [comment]
Thank you! 

I get an error saying: 
Missing required parameters: [
      clientID: 
]

I think it’s referring to this:
const azureAuth = new AzureAuth({
  clientID: 'YOUR_CLIENT_ID'
})


Could you help? -Tori

**Comment by ohtoritoritori** [comment]
Do I need to create all similar files to yours? Or is it inclusive with react-native-azure-auth importation? -T

**Comment by vmurin** [comment]
Hi Tory,

I have just added a sample app to github: https://github.com/vmurin/react-native-azure-auth-sample
Hope it can help you along.

Good luck
Vladi

**Comment by vmurin** [comment]
I did not check the iOS version, but the android one runs perfectly on simulator

**Comment by ohtoritoritori** [comment]
Are you using a certain version of yarn or npm? I install npm (I’ve tried yarn as well), and try and run iOS and it says to download npm again in an endless circle. It’s only your project that does this. Thank you for getting back to me. -Tori

**Comment by vmurin** [comment]
1) are you talking about sample project or your own? post the command you are putting in and the error output
2) are you on Mac?
3) the only so to say "special feature" in the 'react-native-azure-auth' project is that one dependency is not published on NPM and given in Github notation:
`"js-base64": "github:vmurin/js-base64"`
it requires interaction of npm and git what could theoretically lead to some side effects on special system configurations. for example on windows with cygwin

**Comment by ohtoritoritori** [comment]
This is for iOS. Below you are using Product_Name… rfc1034identifier… Is this unique to your project or something I need to find and replace? Thanks for your help. I’m new to react native and Microsoft. -Tori

Inside the ios folder open the Info.plist and locate the value for CFBundleIdentifier, e.g.

<key>CFBundleIdentifier</key>
<string>org.reactjs.native.example.$(PRODUCT_NAME:rfc1034identifier)</string>
and then register a URL type entry using the value of CFBundleIdentifier as the value of CFBundleURLSchemes

<key>CFBundleURLTypes</key>
<array>
    <dict>
        <key>CFBundleTypeRole</key>
        <string>None</string>
        <key>CFBundleURLName</key>
        <string>auth0</string>
        <key>CFBundleURLSchemes</key>
        <array>
            <string>org.reactjs.native.example.$(PRODUCT_NAME:rfc1034identifier)</string>
        </array>
    </dict>
</array>

**Comment by ohtoritoritori** [comment]
Also in the sample you say replace with your client id… where is that located? I’m only seeing application id and object id… -Tori

**Comment by vmurin** [comment]
1) about rfc1034identifier see here: https://stackoverflow.com/questions/2468176/should-the-rfc1034identifier-be-removed-from-the-cfbundleidentifier-in-plist-fil
Google is your friend! ;-) So it's just formatting.

2) you have just to create a new section in Info.plist (with CFBundleURLSchemes) as described using the value found for key <key>CFBundleIdentifier</key> -> something between _<string>_

3)
https://github.com/vmurin/react-native-azure-auth-sample/blob/c3dc1ada7cd449d880960f6b32fd7097bbad2799/App.js#L14

This is Client ID  you have to replace with yours from MS registration
