### ISSUE TITLE
How to sign in as other user in iOS

### ISSUE THREAD

**Issue by suresh777** [vmurin/react-native-azure-auth#51]
I have checked closed issues related to this question. But I am looking same behaviour that if i do clear session and  if i try to do userinteraction login it is not even showing login screen.

On logout i have written this method afterthat i am calling login api

 ```
_onLogout = () => {
    azureAuth.webAuth
      .clearSession({options})
      .then(success => {
        this.setState({ accessToken: null, user: null });
      })
      .catch(error => console.log(error));
  };

 _onLogin = async () => {
    try {
      let tokens = await azureAuth.webAuth.authorize({scope: 'openid profile User.Read' })
      console.log('CRED>>>', tokens)
      this.setState({ accessToken: tokens.accessToken });
      let info = await azureAuth.auth.msGraphRequest({token: tokens.accessToken, path: 'me'})
      console.log('info', info)
      this.setState({ user: info.displayName, userId: tokens.userId })
    } catch (error) {
      console.log('Error during Azure operation', error)
    }
  };
```

**Comment by vmurin** [comment]
> it is not even showing login screen
What happens instead?

**Comment by suresh777** [comment]
It is directly logging in means silent login is happening. Here main issue is it is not clearing browser session.

**Comment by vmurin** [comment]
Do you see the browser window at all? You do not have the silent login method call in your code. Or you talking not about the code above?
Do you want to say - browser window opens and closes immediately?

**Comment by suresh777** [comment]
Yes whatever questions you mentioned

**Comment by vmurin** [comment]
OK. I will answer the questions separately.

**1) Silent login**

It is **your** own application ;)  and it is only up to you to do silent or interactive login!!! If you want to remove saved tokens and thereby make the silent login impossible - **just do it!!!**

Add before `clearSession()`:
```javascript
await azureAuth.auth.clearPersistenCache(userId)
```

**1) Interactiv login**

At first take a look at this [comment](https://github.com/vmurin/react-native-azure-auth/issues/46#issuecomment-553112332)

I can not confirm the interactiv login problem. I checked it on android emulator - after logout I am always re-prompted for password!
On logout I get the following two screens and the next login is a normal login also with user name (e-mail) prompt!

1
------------------------

![Screenshot_1573629781](https://user-images.githubusercontent.com/9309490/68743790-841e6e00-05f3-11ea-8f2a-f96878ff9b2e.jpg)

2
------------------------

![Screenshot_1573631379](https://user-images.githubusercontent.com/9309490/68743799-88e32200-05f3-11ea-80ad-4d96d763a09a.jpg)

**Comment by vmurin** [comment]
One another option for interactive login - use `prompt` option on `authorize()` See [docs](https://vmurin.github.io/react-native-azure-auth/WebAuth.html#.authorize) 

```javascript
let tokens = await azureAuth.webAuth.authorize({scope: 'openid profile User.Read', prompt: 'login'})
```

In this case the user will be **always** prompted for name and password and you do not have to logout  in order to login under another user.

I also added explicit option `closeOnLoad` for `clearSession()` method. Before it was `true` by default, but worked only for iOS. Now you can choose by yourself to show logout browser window mentioned in previous comment or not.

With this additions I think the issue is solved. Please reopen if not :)
