### ISSUE TITLE
Crash on some Android devices when calling the "ShowUrl" 

### ISSUE THREAD

**Issue by vmurin** [vmurin/react-native-azure-auth#56]
oferRounds wrote:
> I still have a problem @vmurin – at least on my Pixel emulator, on the "showUrl" method, it chooses the CustomTabsIntent path, and after the user insert their credentials, the broswer just remain hanging on the Microsoft page forever... If I remove it – having it choose the "startNewBrowserActivity" path - it works perfect

Tell me please revisions of the following components you are using:

- Android Emulator
- SDK Platform-Tools
- Android Version/ API Version

And post if possible the screenshot of "hanging MS page"

**Comment by oferRounds** [comment]
Thank you! Will add the info later on today

**Comment by oferRounds** [comment]
![image](https://user-images.githubusercontent.com/1477963/69734209-44996b00-1137-11ea-9f21-cfbad434cca9.png)

- Pixel 3a API 26 Android 8.0
- 
```
compileSdkVersion   = 28
    targetSdkVersion    = 28
    buildToolsVersion   = "28.0.3"
    supportLibVersion   = "28.0.0"
    googlePlayServicesVersion = "16.1.0"
    googlePlayServicesLocationVersion = "16.0.0"
    googlePlayServicesAuthVersion = "16.0.1"
    firebaseVersion = "16.0.4"
    minSdkVersion = 19
```

**Comment by vmurin** [comment]
Hey, I have now tested with your version and still can't reproduce the issue :(
Probably it is some local case. Could you try to wipe data on your emulator (Menu option in AVD Manager) and test again.

**Comment by vmurin** [comment]
Stale issue closed due to inactivity
