### ISSUE TITLE
Microsoft login screen loads endlessly

### ISSUE THREAD

**Issue by tgmcguire** [vmurin/react-native-azure-auth#6]
Hey there!

I'm having an issue with signing in. I've got the package installed and configured – everything seems good to go with no errors or obvious issues. When I sign in with my Microsoft account and reach this screen, it loads endlessly and doesn't present any errors:

<img width="545" alt="screenshot 2018-10-18 08 44 54" src="https://user-images.githubusercontent.com/2480113/47166916-1994e480-d2b2-11e8-9fb3-17d669648cea.png">

Those blue loading dots at the top scroll across forever. This is after clicking "Personal account" – there is no work/school account, so that flow does not work. I've tried another person's Microsoft account and I get the same result here also. I can also log into my Microsoft account via Safari directly on iOS, and on my computer, without trouble – so I don't think it's something on Microsoft's end.

Any assistance that you can provide would be great! =)

**Comment by vmurin** [comment]
Hi Tommy,

I suppose the problem is in call-back-URL: either it is not defined or it is not reachable (the second one is more probable) - so after you are authenticated on MS login page, you should be redirected to call-back and if it not reachable you will see  endlessly loading indicator.
For some web-app the call-back-URL is a real URL with http(s):// scheme. For an RN-app it is custom URL with some custom scheme. If you followed the README the scheme is you BUNDLE_ID (on android). And you must register the scheme in your app (see README for your OS). If the scheme is not registered it could probably also lead to an endless lasting call.
Hope it will help you :)

**Comment by tgmcguire** [comment]
@vmurin Thanks for the speedy response! This is spot on. I had copied the wrong ID over, which obviously caused issues – I didn't even think to look there. Thanks so much!

**Comment by vmurin** [comment]
Glad to help you out!

**Comment by vmurin** [comment]
@Headcult 
Hi, actually it is possible to have the same callback URLs for both systems. But in your case (if Android works) it should be the easy reason - you have to maintain two (both iOS and Android) URLs in Azure App Registration.
Did you have enter the iOS URL into Azure?
Have a nice day!

**Comment by Headcult** [comment]
Thanks for the response. Still not able to figure out the right IDs to use in info.plist and the redirect URLs in Azure.

In my info.plist, here's my Bundle Identifier: org.reactjs.native.example.xxxxx and the same is in my URL schemes as well as seen below:

```
<key>CFBundleIdentifier</key>
	<string>org.reactjs.native.example.xxxxx</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>None</string>
			<key>CFBundleURLName</key>
			<string>auth0</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>org.reactjs.native.example.xxxxx</string>
			</array>
		</dict>
	</array>
```

And in my Azure Redirect URLs, there are two entries for Android and iOS as seen below:

- org.reactjs.native.example.xxxxx://org.reactjs.native.example.xxxxx/ios/callback
- com.xxxxx://com.xxxxx/android/callback

This is as per the Readme for iOS and Android. But still it loads endlessly for iOS and works fine for Android.

Any inputs on how to resolve this? Thanks in advance!

**Comment by Headcult** [comment]
@vmurin Any more pointers on this please?

**Comment by vmurin** [comment]
Point number one:
Take a look at the RN docs https://facebook.github.io/react-native/docs/linking.html
apparently you have to adjust linking code to make it work, depending on iOS version and linking type. I mean the section in README related to `AppDelegate.[swift|m]`

Point number two:
It could be some weird inconsistency in bundle naming   - you better should not use hard-coded strings but variables and just set bundle ID in XCode once.

Example portion for your `plist`  

```xml
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<string>Headcult App $(BUNDLE_NAME_SUFFIX)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>0.3.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>None</string>
			<key>CFBundleURLName</key>
			<string>Headcult App</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
			</array>
		</dict>
	</array>
```
Additional clue:
https://stackoverflow.com/questions/32862253/xcode-7-changing-product-bundle-identifier

**Comment by MirzaArslan123** [comment]
HI Vmurin 
i also face the same issue for some days can you please guide me

i am facing this issue in android emulator

![Screenshot 2023-06-02 at 10 41 52 AM](https://github.com/vmurin/react-native-azure-auth/assets/119283732/39434ef0-3a2c-4cfa-af1d-12216a6fa3f2)
![Screenshot 2023-06-02 at 10 43 17 AM](https://github.com/vmurin/react-native-azure-auth/assets/119283732/a220816e-ba6a-49c8-9f43-d2a6fd4e2ff7)
![Screenshot 2023-06-02 at 10 43 54 AM](https://github.com/vmurin/react-native-azure-auth/assets/119283732/b0bc64ab-09f4-4471-a765-bdfc7f4be03e)
![Screenshot 2023-06-02 at 10 44 46 AM](https://github.com/vmurin/react-native-azure-auth/assets/119283732/7ec61e49-cd68-423c-a446-eec03929d1b8)



but

**Comment by MirzaArslan123** [comment]
@vmurin i am really thankful to you if you respond me fastly

**Comment by MirzaArslan123** [comment]
@vmurin yes i am also try this solution but the error is same

**Comment by iamsaadMehmood** [comment]
remove` android:pathPrefix` from `intent-filter` and update your intent filter to the following it will fix your issue

```
<intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data
              android:host='${applicationid}'
              android:scheme="msauth" />
</intent-filter>
```

**Comment by Monisankarnath** [comment]
Guys I found the solution and it is working with the current version 1.8.9 - [Soln](https://github.com/vmurin/react-native-azure-auth/issues/9#issuecomment-1924727947)
