### ISSUE TITLE
Acquire silent token crashing

### ISSUE THREAD

**Issue by ranshine** [vmurin/react-native-azure-auth#60]
I have taken latest update 1.3.8 version. I logged in with credentials login is working fine. After one hour my token got expired. It tried silent login it showed this error.
![Simulator Screen Shot - iPhone X - 2019-11-29 at 14 57 27](https://user-images.githubusercontent.com/25414755/69874475-16578f00-12e1-11ea-8c6f-38463b7f43af.png)

In 1.3.1 version it worked fine

**Comment by vmurin** [comment]
Thank you very much for reporting the issue! I will take care about it and update the library very soon... probable today :)

**Comment by vmurin** [comment]
Hi,
please try the version 1.3.9 and report what you get. It should either work again or throw another error.

**Comment by ranshine** [comment]
I tried 1.3.9 i got this error 
```
ExceptionsManager.js:126 Error in silent request:  Error: Invalid id: 
    at normalizeId (baseTokenItem.js:17)
    at Function.createAccessTokenKey (baseTokenItem.js:55)
    at TokenCache.getAccessToken$ (cache.js:83)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at tryCatch (runtime.js:45)
    at invoke (runtime.js:135)
    at runtime.js:170
    at tryCallTwo (core.js:45)
```
![Simulator Screen Shot - iPhone X - 2019-12-02 at 13 28 48](https://user-images.githubusercontent.com/25414755/69940267-e0e0ba80-1507-11ea-9d03-d3bc88dea9f7.png)

**Comment by vmurin** [comment]
Perfect! It means you are calling the `acquireTokenSilent()` with totally wrong `userId` !
That's the only reason.
It should be `String`
See the [docs](https://vmurin.github.io/react-native-azure-auth/Auth.html#.acquireTokenSilent)

**Comment by ranshine** [comment]
I am sending string only, i haven't change anything in my code.
I just updated azure auth library 1.3.1 to 1.3.8

**Comment by vmurin** [comment]
The `normalizeId()`  function checks the type of the ID
Look [here](https://github.com/vmurin/react-native-azure-auth/blob/a4ae90a3b6b636828192af918abd9f75609f8717/src/token/baseTokenItem.js#L7)
You see your reported error. 

Earlier your problem was the same: 
>`userId.toLowerCase` is not a function 

i.e. - your `userId` has anther type as `string`
Try to debug the code.

**Comment by vmurin** [comment]
> **Silent token is not working when token got expired.** If it is not expired it is working fine
Is it still the case for the lib. v.1.3.9?
I suppose you should have the error with not expired token either.

**Comment by ranshine** [comment]
yes i am passing some wrong userId. You can close issue
Thanks

**Comment by vmurin** [comment]
Thank you for your feedback! 
And good luck with your app :)
