### ISSUE TITLE
HTTP Error 401.83 - Unauthorized - You do not have permission to view this directory or page

### ISSUE THREAD

**Issue by arcoder** [vmurin/react-native-azure-auth#61]
Hello,
I've registered on Azure 2 Apps called for example SSO and Web:
1. **SSO**: configured with the following settings: **com.mob.app://com.mob.app/android/callback**, implicit (token ID + access token), multitenant
2. **Web**: linked to an App Service which has Azure AD authentication enabled and associated to the **Web** App through the client id (the rapid way).

Scope for the APP **SSO** was updated with **api://18bXXXX..../user_impersonation** (of the **Web** app)

I try to connect to the API of the App Service using the Client ID of the App **SSO** and I get: **HTTP Error 401.83 - Unauthorized**

I use the following method:

`let tokens = await azureAuth.webAuth.authorize({scope: 'openid profile User.Read **api://18bXXXX..../user_impersonation** ' })`      

I successfully got the access token, the rawIdToken, the userId, but, when I try to call my APIs (using Bearer in Authentication header) I receive the above mentioned error.

My function (I removed some lines to keep it simple):
` async getActiveProjects(url) {	
	try {
	  let response = await fetch(url, {
		method: 'GET',
		headers: {
		  mode: 'no-cors',
		  Accept: 'application/json, image/*;q=0.1',
          'Content-Type': 'application/x-www-form-urlencoded',
		  Authorization : 'Bearer ' + this.state.id_token
		}});
	  let responseJson = await response.json();
	} catch (error) {
	  console.error(error);
	}
  }`

Thank you

**Comment by vmurin** [comment]
You have a pretty complicated question not really related to the library. But I'll try help anyway.

If I understand it right, you should use the [on-behalf-of flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow)
What I've noticed - you are using the `id_token` to authorize your service call. Take a look on the referenced doc page. Cite:

> As of May 2018, some implicit-flow derived id_token can't be used for OBO flow. Single-page apps (SPAs) should pass an access token to a middle-tier confidential client to perform OBO flows instead. For more info about which clients can perform OBO calls, see limitations.

So I will close the issue as **not related**. The better place for it is for example the stackoverflow.com ;-)
