### ISSUE TITLE
[Question] - refresh_token is not returned

### ISSUE THREAD

**Issue by ranierimazili** [vmurin/react-native-azure-auth#67]
Hi,

I've developed an app ([the code is here](https://github.com/ranierimazili/react-native-azure-ad-auth-example)) but the refresh_token is never returned.
The returned object is [here](https://www.codepile.net/pile/XRv4bxlG)

Using another library ([react-native-app-auth](https://github.com/FormidableLabs/react-native-app-auth)) it's returned properly.

What am I doing wrong?

**Comment by gec-2000** [comment]
@ranierimazili Try adding console.log after https://github.com/vmurin/react-native-azure-auth/blob/925cf13c0d99df1f528867db95af734e879fabab/src/webauth/index.js#L96-L100 to see if there's really a refresh token returned.

**Comment by vmurin** [comment]
@gec27  thanks for the good tip. I did not figured out, that @ranierimazili could look for the token in the response object of the `authorize()` function. It is not there!

@ranierimazili  the refresh token is processed and saved/cached in background so you do not have it in the method response. But you also do not need it too! If you need a new access token you can just call `acquireTokenSilent()` and the refresh token will be used for you here.

I will close the issue now. @ranierimazili feel free to reopen if the issue still not cleared for you.
