### ISSUE TITLE
Requesting a specific resource

### ISSUE THREAD

**Issue by rwrife** [vmurin/react-native-azure-auth#70]
Is there a way to request a specific resource (ie graph.windows.net) so the audience is set on the return token?  I noticed the aud in the token is set to a random (???) guid and I cannot validate against that in my services.

**Comment by rwrife** [comment]
Figured out my issue, I was trying to scope with https://graph.windows.net/.default and it didn't like mixing that with application specific scopes.

**Comment by vmurin** [comment]
Just for clarification -  what do you mean with "app specific scopes" ? Probably it could be helpful for others...
