### ISSUE TITLE
Jumping to 2FA app causes browser to stop waiting.

### ISSUE THREAD

**Issue by rwrife** [vmurin/react-native-azure-auth#71]
I've noticed on iOS, if you use a 2FA (Microsoft Authenticator) application, when you jump to the 2FA app the browser window that hosted the auth is dead when you return and you get a "Can't end BackgroundTask: no background task exists with identifier 1 (0x1), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug." error and auth ultimately fails because the page is no longer waiting for the signal to continue.

**Comment by vmurin** [comment]
At first sight it sounds like some unrelated issue. I suppose you are on iOS 13  - there are many issues reported related to the new life cycle.

Another possibility - if 2FA uses Safari Controller too - then it could lead to conflict...
Have you tried to debug?

**Comment by rwrife** [comment]
I've been trying to debug it, but I've not gotten anywhere...but from what I've read, the Javascript engine is killed in most of the web containers used in iOS apps to save battery.  There is a SFAuthenticationSession that is for OAuth-like flows, but they may have the same issue if you have to jump to an external 2FA app.  I'm going to ask around with some other mobile teams here at work (Microsoft) to see if they've run into the same issue.

**Comment by vmurin** [comment]
unfortunately I don't have much experience with iOS development and can't say how the chain "RN app" -> "Safari View" -> "2FA app" should/can behave.

Please post here your feedback if you will find out some useful clues

**Comment by rwrife** [comment]
I tried switching to SFAuthenticationSession (as recommended by Apple), but it too has the same issue of the browser killing JS during the 2FA wait....plus it has this annoying pre-prompt before permitting the authentication.

![image](https://user-images.githubusercontent.com/1685329/71857747-87872080-309d-11ea-99f1-1a1b6f33a075.png)

Researching some other apps it looks like some MS apps (Teams specifically) that use MS Authenticator for 2FA and it host the web experience inside the Authenticator app...it's a weird experience but doesn't suffer from the JS stopping since you never put Authenticator in the background after the page loads.

**Comment by vmurin** [comment]
Hi Ryan,

you are the first who reporting this problem. Could you please describe the user experience once more time step by step eventually with couple screenshots. 
So  - you are starting login process, browser window opens, then MS initiate 2FA and redirects to 2FA app - what exactly happens then, what you see in browser and in the app (screenshots)
Thank you in advance!

**Comment by rwrife** [comment]
Here's I've created a video https://youtu.be/tp7fezyrUjI ...my credentials are already cached, so you won't see those entered, but essentially you enter user/pass, then it prompts how to sign in for 2FA (I'm using MS Authenticator), when I click sign in it goes to a page that has Javascript running in a loop (maybe SignalR or Socket.io) waiting for the other app to complete, I get a prompt to jump to the other app, I go there, verify the login and jump back.....when I jump back because of iOS's battery saver it stops that Javascript on the page, so nothing loads.

**Comment by vmurin** [comment]
I'm curious - does the normal safari browser window (started from launcher and not from RN app) behave the same? So if you are logging in through normal browser on iOS, is it possible to finish the login process?

**Comment by vmurin** [comment]
Hi Ryan,

could you please test the new not merged branch /keep-connection (b846e22)
It should fix the issue.

**Comment by Hirurgo** [comment]
### 
![image](https://user-images.githubusercontent.com/24648180/100338328-80d10700-2fe9-11eb-9ffb-00f7e05ca39c.png)

something went wrong =)

**Comment by vmurin** [comment]
@Hirurgo I suppose you are using XCode 9 - you need XCode 10 to be able to build

**Comment by almercier** [comment]
@vmurin @rwrife We are also experiencing this issue, although in a slightly different scenario than the video.

Going directly back to the app by pressing the "back to app" button on old iphones < iphone X or swiping left on the bottom on newer iPhones works and the auth webivew successfully picks up the 2FA approval.

However, it does not pick up the approval when we approve in the 2FA app and then try to go back by app switching (double tapping home and selecting it from the app switcher for example).

**Comment by Egutzwil** [comment]
We are also experiencing the same issues as @almercier.

**Comment by vmurin** [comment]
@almercier Yes, I steel did not get a reliable feedback about keep-connection branch. It would be great if you could test it.

**Comment by almercier** [comment]
@vmurin Can you rebase or merge master into that branch? It's a bit behind currently

**Comment by almercier** [comment]
@vmurin I'm using xcode 12.4 but getting the same semantic errors that @Hirurgo was having...

![image](https://user-images.githubusercontent.com/30079507/110345565-b7f98000-7ffc-11eb-8743-c0a596ffc72f.png)

**Comment by vmurin** [comment]
@almercier I have just rebased the branch on to master and also added one important ;) import 
Try to pull and rebuild the project

**Comment by almercier** [comment]
@vmurin 

Still getting a significant number of semantic errors. Different ones from before though.

![image](https://user-images.githubusercontent.com/30079507/110483499-c062c100-80b7-11eb-8929-dafa54375fd7.png)

**Comment by vmurin** [comment]
@almercier The branch is updated now with correct native code call. Could you take look please.

**Comment by almercier** [comment]
@vmurin Updated branch builds now, but attempting to call authorize now gives me a nonce error from microsoft, whereas I confirmed that switching back to the master branch does not get this error.

```javascript
...
const azureAuth = new AzureAuth({
    clientId: clientId,
    tenant: tenant,
});
let tokens = await azureAuth.webAuth.authorize({
    scope: 'openid profile email',
});
```

![image](https://user-images.githubusercontent.com/30079507/110797838-8d4f3780-8247-11eb-8cfe-be02b537602b.png)

**Comment by almercier** [comment]
@vmurin Maybe it would be worth putting up a PR for that branch so we can continue discussing there instead of in the issue itself?

**Comment by almercier** [comment]
Adding the nonce back that was removed in the commit snippet below seems to have worked
![image](https://user-images.githubusercontent.com/30079507/110801431-4105f680-824b-11eb-9ddb-7e0042d75387.png)

**Comment by vmurin** [comment]
@almercier PR created #111 
Let me know about the main issue test results
