### ISSUE TITLE
Problem with redirect to app.

### ISSUE THREAD

**Issue by Jalson1982** [vmurin/react-native-azure-auth#73]
Hello, I want to implement Microsoft login and ok it works but it does not redirect me-too app. Actually it redirects me back but it does not return any token. When I login into account it offers me ( like you see on the image ) to open it in-app. But when I choose to open app there is no token. What am I doing wrong? Thanks in advance.

<img width="341" alt="Screenshot 2020-01-08 at 16 49 34" src="https://user-images.githubusercontent.com/35011526/71993415-5c383900-3237-11ea-80f3-88e8a618d1ff.png">

**Comment by Jalson1982** [comment]
On android it returns me back with an error even if log in correctly:
"error": "a0.session.user_cancelled", "error_description": "User cancelled the Auth"

**Comment by Jalson1982** [comment]
Solved.

**Comment by vmurin** [comment]
Hi Jalson,

could you please post here the cause/solution you found out. It can help others with similar issue.
Thank you in advance!

Best regards
Vladimir

**Comment by Jalson1982** [comment]
Hi Vlad,

Yes, my issues were that I am using the latest version of RN and need to include in AppDelegate.m this code that is different then one in docs:

// iOS 9.x or newer
#import <React/RCTLinkingManager.h>

- (BOOL)application:(UIApplication *)application
   openURL:(NSURL *)url
   options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  return [RCTLinkingManager application:application openURL:url options:options];
}

**Comment by vmurin** [comment]
Thank you very much! I updated the README too.
