### ISSUE TITLE
Logout Missing Required Parameters

### ISSUE THREAD

**Issue by Nafets94** [vmurin/react-native-azure-auth#76]
I'm having the issue on iOS when I try to logout I get an error screen saying:

```
Missing required parameters: [
 "closeOnLoad"
]
```

What is causing this?

**Comment by vmurin** [comment]
Hi,
sorry, it was a leftover in sample application. See the snippet below:

```js
...
azureAuth.webAuth
      .clearSession()
...
```

There should NOT be any EMPTY  object parameters in the `clearSession()` call.

Feel free to reopen the issue if it did not solve you problem :)
