### ISSUE TITLE
Can this package be used to get and display profile picture?

### ISSUE THREAD

**Issue by zizango123** [vmurin/react-native-azure-auth#77]
Hi,

I am developing a react-native app that authenticates with azure-ad using this package. I am able to get the user profile data for the signedIn user. Can this package be also used to get the profile picture and display it in a react-native Image element

**Comment by vmurin** [comment]
Starting from version 1.4 it is possible to use for example  `await azureAuth.auth.msGraphRequest({token: tokens.accessToken, path: '/me/photo'})` (or other path variations) to get blob files - in this case image.

See also: [https://docs.microsoft.com/de-de/graph/api/profilephoto-get?view=graph-rest-1.0](https://docs.microsoft.com/de-de/graph/api/profilephoto-get?view=graph-rest-1.0)
