### ISSUE TITLE
[Question] Regarding the AccessToken and raw_id_token received.

### ISSUE THREAD

**Issue by Nafets94** [vmurin/react-native-azure-auth#78]
This is not an issue and I'm sorry if this is not the right place to ask this.
I'm new to mobile development in general and wanted to make sure I understand this library flows.

[imgur oauth2 flow](https://i.imgur.com/3zNhedJ.png)

Considering the above flow, the library handles only the red part? So with the accessToken I get back I have to create a post request to /oauth2/token in order to get some other access_token and refresh_token that I can further validate against an API?

Thank you!

**Comment by vmurin** [comment]
Hi,
Thanks for your question. 
Actually library handles everything including caching of tokens for validity time and refreshing them silently (if the scope has not changed) later.
What you have to do is only your Web API calls with current access token.
Just take a look on the sample app [here](https://github.com/vmurin/react-native-azure-auth-sample) to see the whole flow.

By the way the original MS flow diagram implemented can be found here: [https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow)  ;-)

Feel free to reopen the issue if you have further questions

**Comment by Nafets94** [comment]
Hey, thank you for your response and sorry to disturb. I've been looking on that sample before and I simply cannot understand (or find) where the call to /oauth2/token is done.

In my small project I've changed in AzureAuth the tenant = 'common' with a tenant-id from the azure active directory. However after I log in with my credentials it seems the accessToken I receive is not a valid jwt token if I check it in https://jwt.io/.

**Comment by vmurin** [comment]
How can you check validity - you don't have an privat key from Microsoft! ;-)))) (No joke)
The validity can be checked from Azure itself only.
With acquired token you can access all MS services not your own. The token is valid for the scope requested in your code - mail, calender, user profile, one drive etc.
Take a look in MS docs. You can start with [MS Graph](https://developer.microsoft.com/en-us/graph) - it's recommend from MS to request data preferably via this API.

**Comment by olya7viit** [comment]
I found solution. You don't have to create a post request to /oauth2/token in order to get some other access_token and refresh_token. accessToken is access_token. My changes: 
const azureAuth = new AzureAuth({
  clientId: AZURE_CLIENT_ID,
  prompt: "login",
  clientSecret: AZURE_CLIENT_SECRET,
  tenant: AZURE_TENANT_ID,
  scope: ["openid", "profile", "User.Read", "offline_access"],
});

azureAuth.webAuth.authorize({},
  ).then(async (res) => {
    authAccessToken = res.accessToken;
    let info = await azureAuth.auth.msGraphRequest({ token: res.accessToken, path: "/me" });
    return info
  })
