### ISSUE TITLE
Runtime crash on Android: `can not invoke AzureAuth.showUrl`

### ISSUE THREAD

**Issue by oferRounds** [vmurin/react-native-azure-auth#8]
Any idea what might cause it?

**Comment by oferRounds** [comment]
<img width="345" alt="screen shot 2018-12-03 at 17 47 00" src="https://user-images.githubusercontent.com/1477963/49384333-7560e300-f723-11e8-8f19-f2a817c4cea2.png">

**Comment by vmurin** [comment]
Try to consult the working sample project - it is a good point to start with:
https://github.com/vmurin/react-native-azure-auth-sample

**Comment by oferRounds** [comment]
Thanks! I’ll check it out

**Comment by oferRounds** [comment]
Yes! The linking did not completed well. I sometimes encounter this problem with other libraries as well – not sure if it’s a RN’s problem, or the specific library.

Any how, make sure that all the linking steps completely successfully; otherwise, do it manually

**Comment by Domino987** [comment]
I added it to settings.gradle, the package to MainApplication and imported the dependency in build.gradle. Did I miss something?

**Comment by oferRounds** [comment]
No, actually that’s all... Maybe try to clean the project?

**Comment by Domino987** [comment]
Deleted node moduels and tried cleaning but still...
The sample wont even start. 
I will try to figure it out.

**Comment by Domino987** [comment]
I had to update the build version in the library to match my own build version within the build.gradke file.
