### ISSUE TITLE
Promise rejection when getting request back

### ISSUE THREAD

**Issue by bova80** [vmurin/react-native-azure-auth#89]
I have everything set up just like it says, but when I get the request back I'm seeing this error when using simulator:

YellowBox.js:71 Possible Unhandled Promise Rejection (id: 2):
Missing required parameters: Missing required parameters: [
  "code"
]
Missing required parameters: Missing required parameters: [
  "code"
]
    at validate (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:223520:13)
    at Auth.exchange (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:221949:46)
    at WebAuth.authorize$ (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:224790:58)
    at tryCatch (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29293:19)
    at Generator.invoke [as _invoke] (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29469:24)
    at Generator.prototype.<computed> [as next] (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29336:23)
    at tryCatch (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29293:19)
    at invoke (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29369:22)
    at http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:29379:15
    at tryCallOne (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3268:14)

**Comment by vmurin** [comment]
Have you tried the [sample app](https://github.com/vmurin/react-native-azure-auth-sample) or your own? If not the sample - please try it and check if it works.

Generally the error says, that the 'code' parameter is missing in the Azure response. The only possibility for it I see is when the login browser window is closed manually (or in some another way) and you are returning to the app but not via the Azure callback.

If you are using the sample app and it still does not work - please describe the login steps and how it looks like on the emulator. 
Are you using iOS?

**Comment by bova80** [comment]
I’ll try the sample app, but I pulled the code right from it. When I push a button the azure ad login stuff shows up so I login and what not and then after you sign in it disappears and I see that error thrown. This is on iOS, but same thing happens on Android.

**Comment by vmurin** [comment]
A good possibility that the Azure does not return code is some corporate policies. For example some scopes are not allowed... Are you using an organisation account or private?

How can you debug the issue:
Set the breakpoint in this [line](https://github.com/vmurin/react-native-azure-auth/blob/d5064f9eb03eb7f71cf8c7bfe9fa080a6eb4e0f6/src/webauth/index.js#L63) and you will see the response (callback) from Azure - in `redirectUrl`. I suppose there is some error message instead of `code` parameter.

**Comment by bova80** [comment]
@vmurin  I'll try that, was just trying the sample app and it won't run for me, gives a TypeError: undefined is not an object (evaluating 'warnings.length' after the app starts.  Says this error is located at: in YellowBoxListRow....

**Comment by bova80** [comment]
![Screen Shot 2020-04-17 at 10 07 17 AM](https://user-images.githubusercontent.com/3451135/79578218-efcda100-8093-11ea-9bbe-614bb8f9ece5.png)
![Screen Shot 2020-04-17 at 10 08 28 AM](https://user-images.githubusercontent.com/3451135/79578226-f2c89180-8093-11ea-8cad-5517aae04888.png)

**Comment by bova80** [comment]
looks like Microsoft has an example on their page partially using your component, so I'm going to try it out: https://docs.microsoft.com/en-us/graph/tutorials/react-native?tutorial-step=1

**Comment by bova80** [comment]
so their tutorial works, but instead of using the common url I use the one for our tenant and don't do a multi-tenant login, are you able to do that with your component?

**Comment by vmurin** [comment]
just add your own `authorityUrl` in the constructor `AzureAuth`

```js
const azureAuth = new AzureAuth({
    clientId: CLIENT_ID,
    authorityUrl: "https://login.microsoftonline.com/1234567890/oauth2/v2.0/"
  });
```
Replace _1234567890_ with your tenant.

See https://vmurin.github.io/react-native-azure-auth/AzureAuth.html

**Comment by vmurin** [comment]
Hey Corey,

could you please briefly write back the solution you ended up with.
Thanks in advance!
