### ISSUE TITLE
After the login via Chrome, the app is not launched back

### ISSUE THREAD

**Issue by oferRounds** [vmurin/react-native-azure-auth#9]
Is this have to do to with the manifest here:
```
 <data
      android:pathPrefix="/android/${applicationId}/callback"
      android:scheme="${applicationId}" 
 />
```

I get an error on the manifest which says that one `host` must be defined. Which host does it refer to?
Not sure...

**Comment by vmurin** [comment]
Please read the answer to this issue: https://github.com/vmurin/react-native-azure-auth/issues/6
and pay attention to this hint in the README:
> The applicationId here should be the same as your app package name, and not the ID from MS App Portal.

These points are only what does matter here.
It works definitely also without  the _android:host_ manifest attribute.

**Comment by Monisankarnath** [comment]
Guys I found the solution. So, when I created the app in azure b2c they asked to add package name and bundle_id_identifier for android and ios respectively. Depending on your naming it can be like com.project.demo or anything separate.
Now azure will provide us redirectUri from those and a hash as well for android. 

Back in your react native project we need to add some configs for linking -
For IOS in info.plist file - 
<dict>
        	<key>CFBundleTypeRole</key>
    		<string>None</string>
    		<key>CFBundleURLName</key>
    		<string>AzureAuth</string>
    		<key>CFBundleURLSchemes</key>
        	<array>
            	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
        	</array>
    	</dict>

For android in AndroidManifest.xml - 
<intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="msauth"
                    android:host="com.project.demo"
                    android:path="/hash"/> 
            </intent-filter>

Now while azureAuth instance creation -
new AzureAuth({
      clientId: "xxxxxxxxx",
      redirectUri: Platform.select({android: redirect_uri_android, ios: redirect_uri_ios}),
      authorityUrl: 'abcd', // optional, to use the custom domain and deployed site
      tenant: "abcd",// optional, custom tenant
    });

This solved the problem with my recent setup. Hope it helps everyone. If anyone got any question you can connect with me through linkedin.
