### ISSUE TITLE
null is not an object evaluating azureauth.bundleidentifier

### ISSUE THREAD

**Issue by owaisbakhtiar** [vmurin/react-native-azure-auth#91]
![Simulator Screen Shot - iPhone 11 - 2020-04-23 at 17 56 01](https://user-images.githubusercontent.com/39827123/80102070-b8775c80-858b-11ea-8db5-8966a120c5c4.png)
Anyone faced this issue? If yes please let me know the solution

**Comment by vmurin** [comment]
It seems you have not linked the native modules. The `AzureAuth` here is a native module and not an instance of the library JS class.
See README. The command: 

```bash
react-native link react-native-azure-auth
```

Please give me a feedback.. :)

**Comment by owaisbakhtiar** [comment]
I have run this command 
react-native link react-native-azure-auth
However when I try pod install it gives me the error shown in screenshot attached
![Screenshot 2020-04-24 at 11 19 08 PM](https://user-images.githubusercontent.com/39827123/80244336-31f17680-8682-11ea-9b06-ef4fcc9bedc3.png)

**Comment by vmurin** [comment]
Look, hier is the [podspec file](https://github.com/vmurin/react-native-azure-auth/blob/master/ios/AzureAuth.podspec) for library.

This question is actually not related to the library itself, but to iOS development. I recommend to look up on the stackoverflow.com

Im closing the issue for now as not related.

**Comment by owaisbakhtiar** [comment]
Thanks brother, The pod spec issue is resolved
I changed 
pod 'AzureAuth', :path => '../node_modules/react-native-azure-auth'
to
pod 'AzureAuth', :path => '../node_modules/react-native-azure-auth/ios' 
now pod install resolved the issue.

**Comment by vmurin** [comment]
👍👍👍🙂
