### ISSUE TITLE
The provided value for the input parameter 'response_type' is not valid

### ISSUE THREAD

**Issue by i-sbaral** [vmurin/react-native-azure-auth#92]
![Screen Shot 2020-05-11 at 12 15 28 am](https://user-images.githubusercontent.com/43529314/81501614-b13aa780-931c-11ea-9ece-a84e8328f239.png)
Hi, hoping someone can help me out here. I am trying to run the example github code for for my app where i have replaced the client id with my client Id . but im getting the following error:

Error during Azure operation [unsupported_response_type: The provided value for the input parameter 'response_type' is not valid. Expected values are the following: 'code', 'token', 'none'. 'id_token' is disabled for this app.]

PS: I couldnt perform this step :"Select checkbox ID tokens in the Implicit grant section - it is needed for OpenID Connect. The library will still use authorization grant and not imlicit."

I couldnt find the implicit grant section . Is this the cause of the issue? if so , can anyone tell me where can i select the ID tokens.

**Comment by vmurin** [comment]
Hi Siddhartha,

What do you have above of the header "Supported Account Types"? Sie my screenshot below - the check-box is exactly above it

![2020-05-10_212941](https://user-images.githubusercontent.com/9309490/81508622-66f9fc00-9305-11ea-8667-ece198929852.jpg)

**Comment by i-sbaral** [comment]
Hi vmurin ,

Thank you for your quick response. I wasnt seeing anything above the Supported Account types.

I managed to solve this issue by explicitly changing the "oauth2AllowIdTokenImplicitFlow" && "oauth2AllowImplicitFlow" values to true in the manifest Json after which  the checkboxes started appearing above the Supported Account types section.

**Comment by vmurin** [comment]
Thank you for your feedback!
