### ISSUE TITLE
The provided value for the input parameter 'response_type' is not valid

### ISSUE THREAD

**Issue by dhruvatara** [vmurin/react-native-azure-auth#93]
Issue is caused on importing the react-native-azure-auth package into a RN app, and calling the azureAuth.webAuth.authorize function

![issue](https://user-images.githubusercontent.com/36121933/85823776-0eef4b80-b733-11ea-8de7-1ae2f5032d14.png)

**Comment by vmurin** [comment]
This is duplicate of issue #92 
Take a look on #88 too

Currently id_token is really required - so you should enable it in your app regitration
