### ISSUE TITLE
The reply URL specified does not match

### ISSUE THREAD

**Issue by ivanmalo** [vmurin/react-native-azure-auth#94]
Hi,

We followed the instructions, but we seem to be missing something in the configuration. When we try to login, we get error AADSTS50011. I attach the screenshots for my Azure config and my manifest. It all seems fine and we've doube checked with other issues, but still no luck. I even set up an extra URL on the Azure config to try and see if I was missing something.

![Screenshot_20200707-223954_Chrome](https://user-images.githubusercontent.com/18297485/86872909-e2c4ba80-c0a2-11ea-8676-290616f523c4.jpg)
![image-1](https://user-images.githubusercontent.com/18297485/86872920-e5bfab00-c0a2-11ea-81e4-2045535e467d.png)
![image](https://user-images.githubusercontent.com/18297485/86872935-ea845f00-c0a2-11ea-824e-7a5ba972ee65.png)

**Comment by vmurin** [comment]
Hi Ivan,

the redirect URl is the one used in authorization call. The library has default URL scheme look [here](https://github.com/vmurin/react-native-azure-auth#android---default-redirect-uri-structure)

In your case you have registered some another URL with the scheme

```
{YOUR_APP_PACKAGE_NAME}://auth/android/callback
```
It is totally different from provided in README and used in library by default and besides this the package name `com.stetamalo.com` does not correspond with one from manifest - `com.stetamalo.vinte`

What you can do:
1. either register URL in the app registration with the  scheme from README - it would be `com.stetamalo.vinte://com.stetamalo.vinte/android/callback` in your case.
Also fix the manifest like this:

```
<intent-filter>
    <action android:name="android.intent.action.VIEW" />
    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />
    <data
        android:pathPrefix="/android/callback"
        android:host="com.stetamalo.vinte"
        android:scheme="com.stetamalo.vinte" />
</intent-filter>
```

2. or you can use **your** custom callback URL. Just provide it as parameter in the class initialization:

```
const azureAuth = new AzureAuth({
    clientId: 'YOUR_CLIENT_ID',
    redirectUri: 'com.stetamalo.com://auth/android/callback'
});
```

See [docs](https://vmurin.github.io/react-native-azure-auth/AzureAuth.html)

Feel free to reopen the issue if this will not help
