### ISSUE TITLE
Are there any plans to support react-native-web?

### ISSUE THREAD

**Issue by Mukhammadali** [vmurin/react-native-azure-auth#97]

**Comment by vmurin** [comment]
Hi Muhammad,

currently is not planed. I consider it later...
I suppose there is no much changes needed - probably only the native function to generate "state", "nonce" and "verifier" should be replaced. The whole rest code base stays unchanged. You just need to use normal web (http/s) callback URLs and that's it.

Any PRs from you are welcome 👍 

Kind regards
Vlad
