### ISSUE TITLE
AzureAuth different sources

### ISSUE THREAD

**Issue by jaltenbernd** [vmurin/react-native-azure-auth#98]
If I run a **pod install** inside the **ios** folder, I get the following error:

[!] There are multiple dependencies with different sources for `AzureAuth` in `Podfile`:
- AzureAuth (from `../node_modules/react-native-azure-auth/ios`)
- AzureAuth (from `../node_modules/react-native-azure-auth`)

The reason I ran the command was because it says it can't find the module **AzureAuth**. Then followed by:

[Sat Aug 15 2020 17:26:57.738]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Sat Aug 15 2020 17:26:58.776]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)

I started with a brand new React Native app and added this module.

**Comment by vmurin** [comment]
Hi John,

I think you issues are not related to the library but to your setup and accident :)

Just take a look on the similar issues on stackoverflow and/or github. See related examples below:

- https://github.com/facebook/react-native/issues/26687
- https://reactnativeforyou.com/module-appregistry-is-not-a-registered-callable-module-calling-runapplication-react-native-error-fix/
- https://stackoverflow.com/questions/59424196/multiple-dependencies-error-during-build-on-ios

Feel free to reopen the issue if you have further questions. I will also extend and slightly improve the pod file shortly.

Regards
Vlad

**Comment by almercier** [comment]
@vmurin I am also getting this error, only for this specific repo. Only the last link you sent is related to the pod install error, and the answer is not useful.

The solutions suggested here also do not resolve the issue. https://github.com/facebook/react-native/issues/26642

the podfile reference is correctly pointing to the root of the module, so it really seems like a possible issue with this module for the latest cocoapods.

**Comment by almercier** [comment]
@vmurin @jaltenbernd The error is resolved by unlinking the two repos that it says to link in the installation instructions. Which tells me it's autolinking and those steps need to be removed from the readme.

**Comment by vmurin** [comment]
> @vmurin @jaltenbernd The error is resolved by unlinking the two repos that it says to link in the installation instructions. Which tells me it's autolinking and those steps need to be removed from the readme.

@almercier Thanks for your suggestion. As a library author I can't know do you use [autolinking](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md)  or not. That's why the README follows the official documentation for [Automatic linking](https://reactnative.dev/docs/linking-libraries-ios) (dont mix up with autolinking ;-))  )

But I will add the note about autolinking issue.
Thank you again!
